#!/usr/bin/env python

from __future__ import print_function
import sys
import os
import argparse


def error(msg):
    sys.exit('Error: ' + msg)

def warning(msg):
    sys.stderr.write('Warning: ' + msg + '\n')


# Parsing arguments.

usage= 'profile_analyse.py profile labels [scope] [-l|--local] [-r|--rom] [-m|--macro] [-a|--all]'
usage += "\n\tprofile     - profiler log generated by FUSE emulator"
usage += "\n\tlabels      - labels list in UnrealSpeccy format (can be generated by SjASMPlus)"
usage += "\n\tscope       - limits all calculations to scope[.*] labels"
usage += "\n\t-l, --local - no not exclude local labels"
usage += "\n\t-r, --rom   - no not exclude labels that are below 0x4000 (usually theese are not real labels but constants)"
usage += "\n\t-m, --macro - no not exclude labels inside MACRO (usually they just litter labels namespace)"
usage += "\n\t-a, --all   - use all labels from list (equivalent to -lrm)"

parser = argparse.ArgumentParser(add_help = False, usage = usage)
parser.add_argument('profile')
parser.add_argument('labels')
parser.add_argument('scope', nargs = '?')
parser.add_argument('-l', '--local', action = 'store_true')
parser.add_argument('-r', '--rom', action = 'store_true')
parser.add_argument('-m', '--macro', action = 'store_true')
parser.add_argument('-a', '--all', action = 'store_true')
args = parser.parse_args()

for filename in args.profile, args.labels:
    if not os.path.isfile(filename):
        error('File "%s" not found.' % filename)

match = 0
if os.path.splitext(args.profile)[1] == '.profile':
    match += 1
if os.path.splitext(args.profile)[1] == '.l':
    match -= 1
if os.path.splitext(args.labels)[1] == '.l':
    match += 1
if os.path.splitext(args.labels)[1] == '.profile':
    match -= 1
if match < 0:
    args.profile, args.labels = args.labels, args.profile

if args.all:
    args.local = args.rom = args.macro = True


# Loading profile.

profile = [0] * 0x10000

with open(args.profile) as f:
    n = 0
    for line in f:
        n += 1
        try:
            line = line.strip()

            addr, time = line.split(',')
            addr = int(addr.strip(), 0)
            time = int(time.strip(), 0)

            if addr < 0 or addr >= 0x10000 or time < 0:
                raise ValueError()

            profile[addr] += time
        except ValueError:
            warning('Incorrect line #%d (\"%s\") in file \"%s\" skipped.' % (n, line, args.profile))


# Loading labels.

labels = {}

with open(args.labels) as f:
    n = 0
    for line in f:
        n += 1
        try:
            line = line.strip()

            addr, label = line.split()
            page, offset = [part.strip() for part in addr.split(':')]

            page = ('07', '05', '02', '00').index(page) if page else 0
            offset = int(offset, 16)

            if not 0 <= offset < 0x4000:
                raise ValueError()

            addr = page * 0x4000 + offset

            if not args.rom and addr < 0x4000:
                continue
            if not args.macro and '>' in label:
                continue

            if addr not in labels:
                labels[addr] = [label]
            else:
                labels[addr].append(label)
        except ValueError:
            warning('Incorrect line #%d (\"%s\") in file \"%s\" skipped.' % (n, line, args.labels))


# Filtering out local labels.

if not args.local:
    labels_list = [l for ll in labels.values() for l in ll if l != args.scope]
    new_labels = {}

    for addr in labels:
        ll = [l for l in labels[addr] if '.' not in l or '.'.join(l.split('.')[:-1]) not in labels_list or l == args.scope]
        if ll:
            new_labels[addr] = ll

    labels = new_labels


# Adding ROM and RAM start labels.

if 0 not in labels:
    labels[0] = ['ROM']
if 0x4000 not in labels:
    labels[0x4000] = ['RAM']


# Calculating time spent between labels.

times = {}
total = 0

addrs = sorted(labels)
for i in range(len(addrs)):
    if args.scope:
        if not any([label == args.scope or label.startswith(args.scope + '.') for label in labels[addrs[i]]]):
            continue

    beg = addrs[i]
    end = addrs[i+1] if i+1 < len(addrs) else len(profile)

    time = sum(profile[beg:end])

    times[beg] = time
    total += time

if not times:
    error('Label(s) not found.')


# Printing results.

if args.scope:
    print('Mask: %s[.*]\n' % args.scope)

for addr in sorted(times):
    for label in labels[addr]:
        print(label)

    time = times[addr]
    percent = 100 * time / total if total > 0 else 0

    if time > 0:
        print('\t%02d%% (%dt)' % (percent, time))
    else:
        print()
if time > 0:
    print()

print('Total: %dt' % total)
