opcodes = [None] * 256 + [0]

opcodes[0x00] = {'size': 1, 'asm': 'NOP'}
opcodes[0x01] = {'size': 3, 'asm': 'LD BC,%'}
opcodes[0x02] = {'size': 1, 'asm': 'LD (BC),A'}
opcodes[0x03] = {'size': 1, 'asm': 'INC BC'}
opcodes[0x04] = {'size': 1, 'asm': 'INC B'}
opcodes[0x05] = {'size': 1, 'asm': 'DEC B'}
opcodes[0x06] = {'size': 2, 'asm': 'LD B,%'}
opcodes[0x07] = {'size': 1, 'asm': 'RLCA'}
opcodes[0x08] = {'size': 1, 'asm': "EX AF,AF'"}
opcodes[0x09] = {'size': 1, 'asm': 'ADD HL,BC'}
opcodes[0x0A] = {'size': 1, 'asm': 'LD A,(BC)'}
opcodes[0x0B] = {'size': 1, 'asm': 'DEC BC'}
opcodes[0x0C] = {'size': 1, 'asm': 'INC C'}
opcodes[0x0D] = {'size': 1, 'asm': 'DEC C'}
opcodes[0x0E] = {'size': 2, 'asm': 'LD C,%'}
opcodes[0x0F] = {'size': 1, 'asm': 'RRCA'}

opcodes[0x10] = {'size': 2, 'asm': 'DJNZ %'}
opcodes[0x11] = {'size': 3, 'asm': 'LD DE,%'}
opcodes[0x12] = {'size': 1, 'asm': 'LD (DE),A'}
opcodes[0x13] = {'size': 1, 'asm': 'INC DE'}
opcodes[0x14] = {'size': 1, 'asm': 'INC D'}
opcodes[0x15] = {'size': 1, 'asm': 'DEC D'}
opcodes[0x16] = {'size': 2, 'asm': 'LD D,%'}
opcodes[0x17] = {'size': 1, 'asm': 'RLA'}
opcodes[0x18] = {'size': 2, 'asm': 'JR %'}
opcodes[0x19] = {'size': 1, 'asm': 'ADD HL,DE'}
opcodes[0x1A] = {'size': 1, 'asm': 'LD A,(DE)'}
opcodes[0x1B] = {'size': 1, 'asm': 'DEC DE'}
opcodes[0x1C] = {'size': 1, 'asm': 'INC E'}
opcodes[0x1D] = {'size': 1, 'asm': 'DEC E'}
opcodes[0x1E] = {'size': 2, 'asm': 'LD E,%'}
opcodes[0x1F] = {'size': 1, 'asm': 'RRA'}

opcodes[0x20] = {'size': 2, 'asm': 'JR NZ,%'}
opcodes[0x21] = {'size': 3, 'asm': 'LD HL,%'}
opcodes[0x22] = {'size': 3, 'asm': 'LD (%),HL'}
opcodes[0x23] = {'size': 1, 'asm': 'INC HL'}
opcodes[0x24] = {'size': 1, 'asm': 'INC H'}
opcodes[0x25] = {'size': 1, 'asm': 'DEC H'}
opcodes[0x26] = {'size': 2, 'asm': 'LD H,%'}
opcodes[0x27] = {'size': 1, 'asm': 'DAA'}
opcodes[0x28] = {'size': 2, 'asm': 'JR Z,%'}
opcodes[0x29] = {'size': 1, 'asm': 'ADD HL,HL'}
opcodes[0x2A] = {'size': 3, 'asm': 'LD HL,(%)'}
opcodes[0x2B] = {'size': 1, 'asm': 'DEC HL'}
opcodes[0x2C] = {'size': 1, 'asm': 'INC L'}
opcodes[0x2D] = {'size': 1, 'asm': 'DEC L'}
opcodes[0x2E] = {'size': 2, 'asm': 'LD L,%'}
opcodes[0x2F] = {'size': 1, 'asm': 'CPL'}

opcodes[0x30] = {'size': 2, 'asm': 'JR NC,%'}
opcodes[0x31] = {'size': 3, 'asm': 'LD SP,%'}
opcodes[0x32] = {'size': 3, 'asm': 'LD (%),A'}
opcodes[0x33] = {'size': 1, 'asm': 'INC SP'}
opcodes[0x34] = {'size': 1, 'asm': 'INC (HL)'}
opcodes[0x35] = {'size': 1, 'asm': 'DEC (HL)'}
opcodes[0x36] = {'size': 2, 'asm': 'LD (HL),%'}
opcodes[0x37] = {'size': 1, 'asm': 'SCF'}
opcodes[0x38] = {'size': 2, 'asm': 'JR C,%'}
opcodes[0x39] = {'size': 1, 'asm': 'ADD HL,SP'}
opcodes[0x3A] = {'size': 3, 'asm': 'LD A,(%)'}
opcodes[0x3B] = {'size': 1, 'asm': 'DEC SP'}
opcodes[0x3C] = {'size': 1, 'asm': 'INC A'}
opcodes[0x3D] = {'size': 1, 'asm': 'DEC A'}
opcodes[0x3E] = {'size': 2, 'asm': 'LD A,%'}
opcodes[0x3F] = {'size': 1, 'asm': 'CCF'}

opcodes[0x40] = {'size': 1, 'asm': 'LD B,B'}
opcodes[0x41] = {'size': 1, 'asm': 'LD B,C'}
opcodes[0x42] = {'size': 1, 'asm': 'LD B,D'}
opcodes[0x43] = {'size': 1, 'asm': 'LD B,E'}
opcodes[0x44] = {'size': 1, 'asm': 'LD B,H'}
opcodes[0x45] = {'size': 1, 'asm': 'LD B,L'}
opcodes[0x46] = {'size': 1, 'asm': 'LD B,(HL)'}
opcodes[0x47] = {'size': 1, 'asm': 'LD B,A'}
opcodes[0x48] = {'size': 1, 'asm': 'LD C,B'}
opcodes[0x49] = {'size': 1, 'asm': 'LD C,C'}
opcodes[0x4A] = {'size': 1, 'asm': 'LD C,D'}
opcodes[0x4B] = {'size': 1, 'asm': 'LD C,E'}
opcodes[0x4C] = {'size': 1, 'asm': 'LD C,H'}
opcodes[0x4D] = {'size': 1, 'asm': 'LD C,L'}
opcodes[0x4E] = {'size': 1, 'asm': 'LD C,(HL)'}
opcodes[0x4F] = {'size': 1, 'asm': 'LD C,A'}

opcodes[0x50] = {'size': 1, 'asm': 'LD D,B'}
opcodes[0x51] = {'size': 1, 'asm': 'LD D,C'}
opcodes[0x52] = {'size': 1, 'asm': 'LD D,D'}
opcodes[0x53] = {'size': 1, 'asm': 'LD D,E'}
opcodes[0x54] = {'size': 1, 'asm': 'LD D,H'}
opcodes[0x55] = {'size': 1, 'asm': 'LD D,L'}
opcodes[0x56] = {'size': 1, 'asm': 'LD D,(HL)'}
opcodes[0x57] = {'size': 1, 'asm': 'LD D,A'}
opcodes[0x58] = {'size': 1, 'asm': 'LD E,B'}
opcodes[0x59] = {'size': 1, 'asm': 'LD E,C'}
opcodes[0x5A] = {'size': 1, 'asm': 'LD E,D'}
opcodes[0x5B] = {'size': 1, 'asm': 'LD E,E'}
opcodes[0x5C] = {'size': 1, 'asm': 'LD E,H'}
opcodes[0x5D] = {'size': 1, 'asm': 'LD E,L'}
opcodes[0x5E] = {'size': 1, 'asm': 'LD E,(HL)'}
opcodes[0x5F] = {'size': 1, 'asm': 'LD E,A'}

opcodes[0x60] = {'size': 1, 'asm': 'LD H,B'}
opcodes[0x61] = {'size': 1, 'asm': 'LD H,C'}
opcodes[0x62] = {'size': 1, 'asm': 'LD H,D'}
opcodes[0x63] = {'size': 1, 'asm': 'LD H,E'}
opcodes[0x64] = {'size': 1, 'asm': 'LD H,H'}
opcodes[0x65] = {'size': 1, 'asm': 'LD H,L'}
opcodes[0x66] = {'size': 1, 'asm': 'LD H,(HL)'}
opcodes[0x67] = {'size': 1, 'asm': 'LD H,A'}
opcodes[0x68] = {'size': 1, 'asm': 'LD L,B'}
opcodes[0x69] = {'size': 1, 'asm': 'LD L,C'}
opcodes[0x6A] = {'size': 1, 'asm': 'LD L,D'}
opcodes[0x6B] = {'size': 1, 'asm': 'LD L,E'}
opcodes[0x6C] = {'size': 1, 'asm': 'LD L,H'}
opcodes[0x6D] = {'size': 1, 'asm': 'LD L,L'}
opcodes[0x6E] = {'size': 1, 'asm': 'LD L,(HL)'}
opcodes[0x6F] = {'size': 1, 'asm': 'LD L,A'}

opcodes[0x70] = {'size': 1, 'asm': 'LD (HL),B'}
opcodes[0x71] = {'size': 1, 'asm': 'LD (HL),C'}
opcodes[0x72] = {'size': 1, 'asm': 'LD (HL),D'}
opcodes[0x73] = {'size': 1, 'asm': 'LD (HL),E'}
opcodes[0x74] = {'size': 1, 'asm': 'LD (HL),H'}
opcodes[0x75] = {'size': 1, 'asm': 'LD (HL),L'}
opcodes[0x76] = {'size': 1, 'asm': 'HALT'}
opcodes[0x77] = {'size': 1, 'asm': 'LD (HL),A'}
opcodes[0x78] = {'size': 1, 'asm': 'LD A,B'}
opcodes[0x79] = {'size': 1, 'asm': 'LD A,C'}
opcodes[0x7A] = {'size': 1, 'asm': 'LD A,D'}
opcodes[0x7B] = {'size': 1, 'asm': 'LD A,E'}
opcodes[0x7C] = {'size': 1, 'asm': 'LD A,H'}
opcodes[0x7D] = {'size': 1, 'asm': 'LD A,L'}
opcodes[0x7E] = {'size': 1, 'asm': 'LD A,(HL)'}
opcodes[0x7F] = {'size': 1, 'asm': 'LD A,A'}

opcodes[0x80] = {'size': 1, 'asm': 'ADD B'}
opcodes[0x81] = {'size': 1, 'asm': 'ADD C'}
opcodes[0x82] = {'size': 1, 'asm': 'ADD D'}
opcodes[0x83] = {'size': 1, 'asm': 'ADD E'}
opcodes[0x84] = {'size': 1, 'asm': 'ADD H'}
opcodes[0x85] = {'size': 1, 'asm': 'ADD L'}
opcodes[0x86] = {'size': 1, 'asm': 'ADD (HL)'}
opcodes[0x87] = {'size': 1, 'asm': 'ADD A'}
opcodes[0x88] = {'size': 1, 'asm': 'ADC B'}
opcodes[0x89] = {'size': 1, 'asm': 'ADC C'}
opcodes[0x8A] = {'size': 1, 'asm': 'ADC D'}
opcodes[0x8B] = {'size': 1, 'asm': 'ADC E'}
opcodes[0x8C] = {'size': 1, 'asm': 'ADC H'}
opcodes[0x8D] = {'size': 1, 'asm': 'ADC L'}
opcodes[0x8E] = {'size': 1, 'asm': 'ADC (HL)'}
opcodes[0x8F] = {'size': 1, 'asm': 'ADC A'}

opcodes[0x90] = {'size': 1, 'asm': 'SUB B'}
opcodes[0x91] = {'size': 1, 'asm': 'SUB C'}
opcodes[0x92] = {'size': 1, 'asm': 'SUB D'}
opcodes[0x93] = {'size': 1, 'asm': 'SUB E'}
opcodes[0x94] = {'size': 1, 'asm': 'SUB H'}
opcodes[0x95] = {'size': 1, 'asm': 'SUB L'}
opcodes[0x96] = {'size': 1, 'asm': 'SUB (HL)'}
opcodes[0x97] = {'size': 1, 'asm': 'SUB A'}
opcodes[0x98] = {'size': 1, 'asm': 'SBC B'}
opcodes[0x99] = {'size': 1, 'asm': 'SBC C'}
opcodes[0x9A] = {'size': 1, 'asm': 'SBC D'}
opcodes[0x9B] = {'size': 1, 'asm': 'SBC E'}
opcodes[0x9C] = {'size': 1, 'asm': 'SBC H'}
opcodes[0x9D] = {'size': 1, 'asm': 'SBC L'}
opcodes[0x9E] = {'size': 1, 'asm': 'SBC (HL)'}
opcodes[0x9F] = {'size': 1, 'asm': 'SBC A'}

opcodes[0xA0] = {'size': 1, 'asm': 'AND B'}
opcodes[0xA1] = {'size': 1, 'asm': 'AND C'}
opcodes[0xA2] = {'size': 1, 'asm': 'AND D'}
opcodes[0xA3] = {'size': 1, 'asm': 'AND E'}
opcodes[0xA4] = {'size': 1, 'asm': 'AND H'}
opcodes[0xA5] = {'size': 1, 'asm': 'AND L'}
opcodes[0xA6] = {'size': 1, 'asm': 'AND (HL)'}
opcodes[0xA7] = {'size': 1, 'asm': 'AND A'}
opcodes[0xA8] = {'size': 1, 'asm': 'XOR B'}
opcodes[0xA9] = {'size': 1, 'asm': 'XOR C'}
opcodes[0xAA] = {'size': 1, 'asm': 'XOR D'}
opcodes[0xAB] = {'size': 1, 'asm': 'XOR E'}
opcodes[0xAC] = {'size': 1, 'asm': 'XOR H'}
opcodes[0xAD] = {'size': 1, 'asm': 'XOR L'}
opcodes[0xAE] = {'size': 1, 'asm': 'XOR (HL)'}
opcodes[0xAF] = {'size': 1, 'asm': 'XOR A'}

opcodes[0xB0] = {'size': 1, 'asm': 'OR B'}
opcodes[0xB1] = {'size': 1, 'asm': 'OR C'}
opcodes[0xB2] = {'size': 1, 'asm': 'OR D'}
opcodes[0xB3] = {'size': 1, 'asm': 'OR E'}
opcodes[0xB4] = {'size': 1, 'asm': 'OR H'}
opcodes[0xB5] = {'size': 1, 'asm': 'OR L'}
opcodes[0xB6] = {'size': 1, 'asm': 'OR (HL)'}
opcodes[0xB7] = {'size': 1, 'asm': 'OR A'}
opcodes[0xB8] = {'size': 1, 'asm': 'CP B'}
opcodes[0xB9] = {'size': 1, 'asm': 'CP C'}
opcodes[0xBA] = {'size': 1, 'asm': 'CP D'}
opcodes[0xBB] = {'size': 1, 'asm': 'CP E'}
opcodes[0xBC] = {'size': 1, 'asm': 'CP H'}
opcodes[0xBD] = {'size': 1, 'asm': 'CP L'}
opcodes[0xBE] = {'size': 1, 'asm': 'CP (HL)'}
opcodes[0xBF] = {'size': 1, 'asm': 'CP A'}

opcodes[0xC0] = {'size': 1, 'asm': 'RET NZ'}
opcodes[0xC1] = {'size': 1, 'asm': 'POP BC'}
opcodes[0xC2] = {'size': 3, 'asm': 'JP NZ,%'}
opcodes[0xC3] = {'size': 3, 'asm': 'JP %'}
opcodes[0xC4] = {'size': 3, 'asm': 'CALL NZ,%'}
opcodes[0xC5] = {'size': 1, 'asm': 'PUSH BC'}
opcodes[0xC6] = {'size': 2, 'asm': 'ADD %'}
opcodes[0xC7] = {'size': 1, 'asm': 'RST 00h'}
opcodes[0xC8] = {'size': 1, 'asm': 'RET Z'}
opcodes[0xC9] = {'size': 1, 'asm': 'RET'}
opcodes[0xCA] = {'size': 3, 'asm': 'JP Z,%'}
opcodes[0xCB] = [None] * 256 + [0]
opcodes[0xCC] = {'size': 3, 'asm': 'CALL Z,%'}
opcodes[0xCD] = {'size': 3, 'asm': 'CALL %'}
opcodes[0xCE] = {'size': 2, 'asm': 'ADC %'}
opcodes[0xCF] = {'size': 1, 'asm': 'RST 08h'}

opcodes[0xD0] = {'size': 1, 'asm': 'RET NC'}
opcodes[0xD1] = {'size': 1, 'asm': 'POP DE'}
opcodes[0xD2] = {'size': 3, 'asm': 'JP NC,%'}
opcodes[0xD3] = {'size': 2, 'asm': 'OUT (%),A'}
opcodes[0xD4] = {'size': 3, 'asm': 'CALL NC,%'}
opcodes[0xD5] = {'size': 1, 'asm': 'PUSH DE'}
opcodes[0xD6] = {'size': 2, 'asm': 'SUB %'}
opcodes[0xD7] = {'size': 1, 'asm': 'RST 10h'}
opcodes[0xD8] = {'size': 1, 'asm': 'RET C'}
opcodes[0xD9] = {'size': 1, 'asm': 'EXX'}
opcodes[0xDA] = {'size': 3, 'asm': 'JP C,%'}
opcodes[0xDB] = {'size': 2, 'asm': 'IN A,(%)'}
opcodes[0xDC] = {'size': 3, 'asm': 'CALL C,%'}
opcodes[0xDD] = [None] * 256 + [0]
opcodes[0xDE] = {'size': 2, 'asm': 'SBC %'}
opcodes[0xDF] = {'size': 1, 'asm': 'RST 18h'}

opcodes[0xE0] = {'size': 1, 'asm': 'RET PO'}
opcodes[0xE1] = {'size': 1, 'asm': 'POP HL'}
opcodes[0xE2] = {'size': 3, 'asm': 'JP PO,%'}
opcodes[0xE3] = {'size': 1, 'asm': 'EX (SP),HL'}
opcodes[0xE4] = {'size': 3, 'asm': 'CALL PO,%'}
opcodes[0xE5] = {'size': 1, 'asm': 'PUSH HL'}
opcodes[0xE6] = {'size': 2, 'asm': 'AND %'}
opcodes[0xE7] = {'size': 1, 'asm': 'RST 20h'}
opcodes[0xE8] = {'size': 1, 'asm': 'RET PE'}
opcodes[0xE9] = {'size': 1, 'asm': 'JP (HL)'}
opcodes[0xEA] = {'size': 3, 'asm': 'JP PE,%'}
opcodes[0xEB] = {'size': 1, 'asm': 'EX DE,HL'}
opcodes[0xEC] = {'size': 3, 'asm': 'CALL PE,%'}
opcodes[0xED] = [None] * 256 + [0]
opcodes[0xEE] = {'size': 2, 'asm': 'XOR %'}
opcodes[0xEF] = {'size': 1, 'asm': 'RST 28h'}

opcodes[0xF0] = {'size': 1, 'asm': 'RET P'}
opcodes[0xF1] = {'size': 1, 'asm': 'POP AF'}
opcodes[0xF2] = {'size': 3, 'asm': 'JP P,%'}
opcodes[0xF3] = {'size': 1, 'asm': 'DI'}
opcodes[0xF4] = {'size': 3, 'asm': 'CALL P,%'}
opcodes[0xF5] = {'size': 1, 'asm': 'PUSH AF'}
opcodes[0xF6] = {'size': 2, 'asm': 'OR %'}
opcodes[0xF7] = {'size': 1, 'asm': 'RST 30h'}
opcodes[0xF8] = {'size': 1, 'asm': 'RET M'}
opcodes[0xF9] = {'size': 1, 'asm': 'LD SP,HL'}
opcodes[0xFA] = {'size': 3, 'asm': 'JP M,%'}
opcodes[0xFB] = {'size': 1, 'asm': 'EI'}
opcodes[0xFC] = {'size': 3, 'asm': 'CALL M,%'}
opcodes[0xFD] = [None] * 256 + [0]
opcodes[0xFE] = {'size': 2, 'asm': 'CP %'}
opcodes[0xFF] = {'size': 1, 'asm': 'RST 38h'}

opcodes[0xED][0x40] = {'size': 2, 'asm': 'IN B,(C)'}
opcodes[0xED][0x41] = {'size': 2, 'asm': 'OUT (C),B'}
opcodes[0xED][0x42] = {'size': 2, 'asm': 'SBC HL,BC'}
opcodes[0xED][0x43] = {'size': 4, 'asm': 'LD (%),BC'}
opcodes[0xED][0x44] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x45] = {'size': 2, 'asm': 'RETN'}
opcodes[0xED][0x46] = {'size': 2, 'asm': 'IM 0'}
opcodes[0xED][0x47] = {'size': 2, 'asm': 'LD I,A'}
opcodes[0xED][0x48] = {'size': 2, 'asm': 'IN C,(C)'}
opcodes[0xED][0x49] = {'size': 2, 'asm': 'OUT (C),C'}
opcodes[0xED][0x4A] = {'size': 2, 'asm': 'ADC HL,BC'}
opcodes[0xED][0x4B] = {'size': 4, 'asm': 'LD BC,(%)'}
opcodes[0xED][0x4C] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x4D] = {'size': 2, 'asm': 'RETI'}
opcodes[0xED][0x4E] = {'size': 2, 'asm': 'IM 0/1'}
opcodes[0xED][0x4F] = {'size': 2, 'asm': 'LD R,A'}

opcodes[0xED][0x50] = {'size': 2, 'asm': 'IN D,(C)'}
opcodes[0xED][0x51] = {'size': 2, 'asm': 'OUT (C),D'}
opcodes[0xED][0x52] = {'size': 2, 'asm': 'SBC HL,DE'}
opcodes[0xED][0x53] = {'size': 4, 'asm': 'LD (%),DE'}
opcodes[0xED][0x54] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x55] = {'size': 2, 'asm': 'RETN'}
opcodes[0xED][0x56] = {'size': 2, 'asm': 'IM 1'}
opcodes[0xED][0x57] = {'size': 2, 'asm': 'LD A,I'}
opcodes[0xED][0x58] = {'size': 2, 'asm': 'IN E,(C)'}
opcodes[0xED][0x59] = {'size': 2, 'asm': 'OUT (C),E'}
opcodes[0xED][0x5A] = {'size': 2, 'asm': 'ADC HL,DE'}
opcodes[0xED][0x5B] = {'size': 4, 'asm': 'LD DE,(%)'}
opcodes[0xED][0x5C] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x5D] = {'size': 2, 'asm': 'RETN'}
opcodes[0xED][0x5E] = {'size': 2, 'asm': 'IM 2'}
opcodes[0xED][0x5F] = {'size': 2, 'asm': 'LD A,R'}

opcodes[0xED][0x60] = {'size': 2, 'asm': 'IN H,(C)'}
opcodes[0xED][0x61] = {'size': 2, 'asm': 'OUT (C),H'}
opcodes[0xED][0x62] = {'size': 2, 'asm': 'SBC HL,HL'}
opcodes[0xED][0x63] = {'size': 4, 'asm': 'LD (%),HL'}
opcodes[0xED][0x64] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x65] = {'size': 2, 'asm': 'RETN'}
opcodes[0xED][0x66] = {'size': 2, 'asm': 'IM 0'}
opcodes[0xED][0x67] = {'size': 2, 'asm': 'RRD'}
opcodes[0xED][0x68] = {'size': 2, 'asm': 'IN L,(C)'}
opcodes[0xED][0x69] = {'size': 2, 'asm': 'OUT (C),L'}
opcodes[0xED][0x6A] = {'size': 2, 'asm': 'ADC HL,HL'}
opcodes[0xED][0x6B] = {'size': 4, 'asm': 'LD HL,(%)'}
opcodes[0xED][0x6C] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x6D] = {'size': 2, 'asm': 'RETN'}
opcodes[0xED][0x6E] = {'size': 2, 'asm': 'IM 0/1'}
opcodes[0xED][0x6F] = {'size': 2, 'asm': 'RLD'}

opcodes[0xED][0x70] = {'size': 2, 'asm': 'IN (C)'}
opcodes[0xED][0x71] = {'size': 2, 'asm': 'OUT (C),0'}
opcodes[0xED][0x72] = {'size': 2, 'asm': 'SBC HL,SP'}
opcodes[0xED][0x73] = {'size': 4, 'asm': 'LD (%),SP'}
opcodes[0xED][0x74] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x75] = {'size': 2, 'asm': 'RETN'}
opcodes[0xED][0x76] = {'size': 2, 'asm': 'IM 1'}
opcodes[0xED][0x78] = {'size': 2, 'asm': 'IN A,(C)'}
opcodes[0xED][0x79] = {'size': 2, 'asm': 'OUT (C),A'}
opcodes[0xED][0x7A] = {'size': 2, 'asm': 'ADC HL,SP'}
opcodes[0xED][0x7B] = {'size': 4, 'asm': 'LD SP,(%)'}
opcodes[0xED][0x7C] = {'size': 2, 'asm': 'NEG'}
opcodes[0xED][0x7D] = {'size': 2, 'asm': 'RETN'}
opcodes[0xED][0x7E] = {'size': 2, 'asm': 'IM 2'}

opcodes[0xED][0xA0] = {'size': 2, 'asm': 'LDI'}
opcodes[0xED][0xA1] = {'size': 2, 'asm': 'CPI'}
opcodes[0xED][0xA2] = {'size': 2, 'asm': 'INI'}
opcodes[0xED][0xA3] = {'size': 2, 'asm': 'OUTI'}
opcodes[0xED][0xA8] = {'size': 2, 'asm': 'LDD'}
opcodes[0xED][0xA9] = {'size': 2, 'asm': 'CPD'}
opcodes[0xED][0xAA] = {'size': 2, 'asm': 'IND'}
opcodes[0xED][0xAB] = {'size': 2, 'asm': 'OUTD'}

opcodes[0xED][0xB0] = {'size': 2, 'asm': 'LDIR'}
opcodes[0xED][0xB1] = {'size': 2, 'asm': 'CPIR'}
opcodes[0xED][0xB2] = {'size': 2, 'asm': 'INIR'}
opcodes[0xED][0xB3] = {'size': 2, 'asm': 'OTIR'}
opcodes[0xED][0xB8] = {'size': 2, 'asm': 'LDDR'}
opcodes[0xED][0xB9] = {'size': 2, 'asm': 'CPDR'}
opcodes[0xED][0xBA] = {'size': 2, 'asm': 'INDR'}
opcodes[0xED][0xBB] = {'size': 2, 'asm': 'OTDR'}

opcodes[0xCB][0x00] = {'size': 2, 'asm': 'RLC B'}
opcodes[0xCB][0x01] = {'size': 2, 'asm': 'RLC C'}
opcodes[0xCB][0x02] = {'size': 2, 'asm': 'RLC D'}
opcodes[0xCB][0x03] = {'size': 2, 'asm': 'RLC E'}
opcodes[0xCB][0x04] = {'size': 2, 'asm': 'RLC H'}
opcodes[0xCB][0x05] = {'size': 2, 'asm': 'RLC L'}
opcodes[0xCB][0x06] = {'size': 2, 'asm': 'RLC (HL)'}
opcodes[0xCB][0x07] = {'size': 2, 'asm': 'RLC A'}
opcodes[0xCB][0x08] = {'size': 2, 'asm': 'RRC B'}
opcodes[0xCB][0x09] = {'size': 2, 'asm': 'RRC C'}
opcodes[0xCB][0x0A] = {'size': 2, 'asm': 'RRC D'}
opcodes[0xCB][0x0B] = {'size': 2, 'asm': 'RRC E'}
opcodes[0xCB][0x0C] = {'size': 2, 'asm': 'RRC H'}
opcodes[0xCB][0x0D] = {'size': 2, 'asm': 'RRC L'}
opcodes[0xCB][0x0E] = {'size': 2, 'asm': 'RRC (HL)'}
opcodes[0xCB][0x0F] = {'size': 2, 'asm': 'RRC A'}

opcodes[0xCB][0x10] = {'size': 2, 'asm': 'RL B'}
opcodes[0xCB][0x11] = {'size': 2, 'asm': 'RL C'}
opcodes[0xCB][0x12] = {'size': 2, 'asm': 'RL D'}
opcodes[0xCB][0x13] = {'size': 2, 'asm': 'RL E'}
opcodes[0xCB][0x14] = {'size': 2, 'asm': 'RL H'}
opcodes[0xCB][0x15] = {'size': 2, 'asm': 'RL L'}
opcodes[0xCB][0x16] = {'size': 2, 'asm': 'RL (HL)'}
opcodes[0xCB][0x17] = {'size': 2, 'asm': 'RL A'}
opcodes[0xCB][0x18] = {'size': 2, 'asm': 'RR B'}
opcodes[0xCB][0x19] = {'size': 2, 'asm': 'RR C'}
opcodes[0xCB][0x1A] = {'size': 2, 'asm': 'RR D'}
opcodes[0xCB][0x1B] = {'size': 2, 'asm': 'RR E'}
opcodes[0xCB][0x1C] = {'size': 2, 'asm': 'RR H'}
opcodes[0xCB][0x1D] = {'size': 2, 'asm': 'RR L'}
opcodes[0xCB][0x1E] = {'size': 2, 'asm': 'RR (HL)'}
opcodes[0xCB][0x1F] = {'size': 2, 'asm': 'RR A'}

opcodes[0xCB][0x20] = {'size': 2, 'asm': 'SLA B'}
opcodes[0xCB][0x21] = {'size': 2, 'asm': 'SLA C'}
opcodes[0xCB][0x22] = {'size': 2, 'asm': 'SLA D'}
opcodes[0xCB][0x23] = {'size': 2, 'asm': 'SLA E'}
opcodes[0xCB][0x24] = {'size': 2, 'asm': 'SLA H'}
opcodes[0xCB][0x25] = {'size': 2, 'asm': 'SLA L'}
opcodes[0xCB][0x26] = {'size': 2, 'asm': 'SLA (HL)'}
opcodes[0xCB][0x27] = {'size': 2, 'asm': 'SLA A'}
opcodes[0xCB][0x28] = {'size': 2, 'asm': 'SRA B'}
opcodes[0xCB][0x29] = {'size': 2, 'asm': 'SRA C'}
opcodes[0xCB][0x2A] = {'size': 2, 'asm': 'SRA D'}
opcodes[0xCB][0x2B] = {'size': 2, 'asm': 'SRA E'}
opcodes[0xCB][0x2C] = {'size': 2, 'asm': 'SRA H'}
opcodes[0xCB][0x2D] = {'size': 2, 'asm': 'SRA L'}
opcodes[0xCB][0x2E] = {'size': 2, 'asm': 'SRA (HL)'}
opcodes[0xCB][0x2F] = {'size': 2, 'asm': 'SRA A'}

opcodes[0xCB][0x30] = {'size': 2, 'asm': 'SLL B'}
opcodes[0xCB][0x31] = {'size': 2, 'asm': 'SLL C'}
opcodes[0xCB][0x32] = {'size': 2, 'asm': 'SLL D'}
opcodes[0xCB][0x33] = {'size': 2, 'asm': 'SLL E'}
opcodes[0xCB][0x34] = {'size': 2, 'asm': 'SLL H'}
opcodes[0xCB][0x35] = {'size': 2, 'asm': 'SLL L'}
opcodes[0xCB][0x36] = {'size': 2, 'asm': 'SLL (HL)'}
opcodes[0xCB][0x37] = {'size': 2, 'asm': 'SLL A'}
opcodes[0xCB][0x38] = {'size': 2, 'asm': 'SRL B'}
opcodes[0xCB][0x39] = {'size': 2, 'asm': 'SRL C'}
opcodes[0xCB][0x3A] = {'size': 2, 'asm': 'SRL D'}
opcodes[0xCB][0x3B] = {'size': 2, 'asm': 'SRL E'}
opcodes[0xCB][0x3C] = {'size': 2, 'asm': 'SRL H'}
opcodes[0xCB][0x3D] = {'size': 2, 'asm': 'SRL L'}
opcodes[0xCB][0x3E] = {'size': 2, 'asm': 'SRL (HL)'}
opcodes[0xCB][0x3F] = {'size': 2, 'asm': 'SRL A'}

opcodes[0xCB][0x40] = {'size': 2, 'asm': 'BIT 0,B'}
opcodes[0xCB][0x41] = {'size': 2, 'asm': 'BIT 0,C'}
opcodes[0xCB][0x42] = {'size': 2, 'asm': 'BIT 0,D'}
opcodes[0xCB][0x43] = {'size': 2, 'asm': 'BIT 0,E'}
opcodes[0xCB][0x44] = {'size': 2, 'asm': 'BIT 0,H'}
opcodes[0xCB][0x45] = {'size': 2, 'asm': 'BIT 0,L'}
opcodes[0xCB][0x46] = {'size': 2, 'asm': 'BIT 0,(HL)'}
opcodes[0xCB][0x47] = {'size': 2, 'asm': 'BIT 0,A'}
opcodes[0xCB][0x48] = {'size': 2, 'asm': 'BIT 1,B'}
opcodes[0xCB][0x49] = {'size': 2, 'asm': 'BIT 1,C'}
opcodes[0xCB][0x4A] = {'size': 2, 'asm': 'BIT 1,D'}
opcodes[0xCB][0x4B] = {'size': 2, 'asm': 'BIT 1,E'}
opcodes[0xCB][0x4C] = {'size': 2, 'asm': 'BIT 1,H'}
opcodes[0xCB][0x4D] = {'size': 2, 'asm': 'BIT 1,L'}
opcodes[0xCB][0x4E] = {'size': 2, 'asm': 'BIT 1,(HL)'}
opcodes[0xCB][0x4F] = {'size': 2, 'asm': 'BIT 1,A'}

opcodes[0xCB][0x50] = {'size': 2, 'asm': 'BIT 2,B'}
opcodes[0xCB][0x51] = {'size': 2, 'asm': 'BIT 2,C'}
opcodes[0xCB][0x52] = {'size': 2, 'asm': 'BIT 2,D'}
opcodes[0xCB][0x53] = {'size': 2, 'asm': 'BIT 2,E'}
opcodes[0xCB][0x54] = {'size': 2, 'asm': 'BIT 2,H'}
opcodes[0xCB][0x55] = {'size': 2, 'asm': 'BIT 2,L'}
opcodes[0xCB][0x56] = {'size': 2, 'asm': 'BIT 2,(HL)'}
opcodes[0xCB][0x57] = {'size': 2, 'asm': 'BIT 2,A'}
opcodes[0xCB][0x58] = {'size': 2, 'asm': 'BIT 3,B'}
opcodes[0xCB][0x59] = {'size': 2, 'asm': 'BIT 3,C'}
opcodes[0xCB][0x5A] = {'size': 2, 'asm': 'BIT 3,D'}
opcodes[0xCB][0x5B] = {'size': 2, 'asm': 'BIT 3,E'}
opcodes[0xCB][0x5C] = {'size': 2, 'asm': 'BIT 3,H'}
opcodes[0xCB][0x5D] = {'size': 2, 'asm': 'BIT 3,L'}
opcodes[0xCB][0x5E] = {'size': 2, 'asm': 'BIT 3,(HL)'}
opcodes[0xCB][0x5F] = {'size': 2, 'asm': 'BIT 3,A'}

opcodes[0xCB][0x60] = {'size': 2, 'asm': 'BIT 4,B'}
opcodes[0xCB][0x61] = {'size': 2, 'asm': 'BIT 4,C'}
opcodes[0xCB][0x62] = {'size': 2, 'asm': 'BIT 4,D'}
opcodes[0xCB][0x63] = {'size': 2, 'asm': 'BIT 4,E'}
opcodes[0xCB][0x64] = {'size': 2, 'asm': 'BIT 4,H'}
opcodes[0xCB][0x65] = {'size': 2, 'asm': 'BIT 4,L'}
opcodes[0xCB][0x66] = {'size': 2, 'asm': 'BIT 4,(HL)'}
opcodes[0xCB][0x67] = {'size': 2, 'asm': 'BIT 4,A'}
opcodes[0xCB][0x68] = {'size': 2, 'asm': 'BIT 5,B'}
opcodes[0xCB][0x69] = {'size': 2, 'asm': 'BIT 5,C'}
opcodes[0xCB][0x6A] = {'size': 2, 'asm': 'BIT 5,D'}
opcodes[0xCB][0x6B] = {'size': 2, 'asm': 'BIT 5,E'}
opcodes[0xCB][0x6C] = {'size': 2, 'asm': 'BIT 5,H'}
opcodes[0xCB][0x6D] = {'size': 2, 'asm': 'BIT 5,L'}
opcodes[0xCB][0x6E] = {'size': 2, 'asm': 'BIT 5,(HL)'}
opcodes[0xCB][0x6F] = {'size': 2, 'asm': 'BIT 5,A'}

opcodes[0xCB][0x70] = {'size': 2, 'asm': 'BIT 6,B'}
opcodes[0xCB][0x71] = {'size': 2, 'asm': 'BIT 6,C'}
opcodes[0xCB][0x72] = {'size': 2, 'asm': 'BIT 6,D'}
opcodes[0xCB][0x73] = {'size': 2, 'asm': 'BIT 6,E'}
opcodes[0xCB][0x74] = {'size': 2, 'asm': 'BIT 6,H'}
opcodes[0xCB][0x75] = {'size': 2, 'asm': 'BIT 6,L'}
opcodes[0xCB][0x76] = {'size': 2, 'asm': 'BIT 6,(HL)'}
opcodes[0xCB][0x77] = {'size': 2, 'asm': 'BIT 6,A'}
opcodes[0xCB][0x78] = {'size': 2, 'asm': 'BIT 7,B'}
opcodes[0xCB][0x79] = {'size': 2, 'asm': 'BIT 7,C'}
opcodes[0xCB][0x7A] = {'size': 2, 'asm': 'BIT 7,D'}
opcodes[0xCB][0x7B] = {'size': 2, 'asm': 'BIT 7,E'}
opcodes[0xCB][0x7C] = {'size': 2, 'asm': 'BIT 7,H'}
opcodes[0xCB][0x7D] = {'size': 2, 'asm': 'BIT 7,L'}
opcodes[0xCB][0x7E] = {'size': 2, 'asm': 'BIT 7,(HL)'}
opcodes[0xCB][0x7F] = {'size': 2, 'asm': 'BIT 7,A'}

opcodes[0xCB][0x80] = {'size': 2, 'asm': 'RES 0,B'}
opcodes[0xCB][0x81] = {'size': 2, 'asm': 'RES 0,C'}
opcodes[0xCB][0x82] = {'size': 2, 'asm': 'RES 0,D'}
opcodes[0xCB][0x83] = {'size': 2, 'asm': 'RES 0,E'}
opcodes[0xCB][0x84] = {'size': 2, 'asm': 'RES 0,H'}
opcodes[0xCB][0x85] = {'size': 2, 'asm': 'RES 0,L'}
opcodes[0xCB][0x86] = {'size': 2, 'asm': 'RES 0,(HL)'}
opcodes[0xCB][0x87] = {'size': 2, 'asm': 'RES 0,A'}
opcodes[0xCB][0x88] = {'size': 2, 'asm': 'RES 1,B'}
opcodes[0xCB][0x89] = {'size': 2, 'asm': 'RES 1,C'}
opcodes[0xCB][0x8A] = {'size': 2, 'asm': 'RES 1,D'}
opcodes[0xCB][0x8B] = {'size': 2, 'asm': 'RES 1,E'}
opcodes[0xCB][0x8C] = {'size': 2, 'asm': 'RES 1,H'}
opcodes[0xCB][0x8D] = {'size': 2, 'asm': 'RES 1,L'}
opcodes[0xCB][0x8E] = {'size': 2, 'asm': 'RES 1,(HL)'}
opcodes[0xCB][0x8F] = {'size': 2, 'asm': 'RES 1,A'}

opcodes[0xCB][0x90] = {'size': 2, 'asm': 'RES 2,B'}
opcodes[0xCB][0x91] = {'size': 2, 'asm': 'RES 2,C'}
opcodes[0xCB][0x92] = {'size': 2, 'asm': 'RES 2,D'}
opcodes[0xCB][0x93] = {'size': 2, 'asm': 'RES 2,E'}
opcodes[0xCB][0x94] = {'size': 2, 'asm': 'RES 2,H'}
opcodes[0xCB][0x95] = {'size': 2, 'asm': 'RES 2,L'}
opcodes[0xCB][0x96] = {'size': 2, 'asm': 'RES 2,(HL)'}
opcodes[0xCB][0x97] = {'size': 2, 'asm': 'RES 2,A'}
opcodes[0xCB][0x98] = {'size': 2, 'asm': 'RES 3,B'}
opcodes[0xCB][0x99] = {'size': 2, 'asm': 'RES 3,C'}
opcodes[0xCB][0x9A] = {'size': 2, 'asm': 'RES 3,D'}
opcodes[0xCB][0x9B] = {'size': 2, 'asm': 'RES 3,E'}
opcodes[0xCB][0x9C] = {'size': 2, 'asm': 'RES 3,H'}
opcodes[0xCB][0x9D] = {'size': 2, 'asm': 'RES 3,L'}
opcodes[0xCB][0x9E] = {'size': 2, 'asm': 'RES 3,(HL)'}
opcodes[0xCB][0x9F] = {'size': 2, 'asm': 'RES 3,A'}

opcodes[0xCB][0xA0] = {'size': 2, 'asm': 'RES 4,B'}
opcodes[0xCB][0xA1] = {'size': 2, 'asm': 'RES 4,C'}
opcodes[0xCB][0xA2] = {'size': 2, 'asm': 'RES 4,D'}
opcodes[0xCB][0xA3] = {'size': 2, 'asm': 'RES 4,E'}
opcodes[0xCB][0xA4] = {'size': 2, 'asm': 'RES 4,H'}
opcodes[0xCB][0xA5] = {'size': 2, 'asm': 'RES 4,L'}
opcodes[0xCB][0xA6] = {'size': 2, 'asm': 'RES 4,(HL)'}
opcodes[0xCB][0xA7] = {'size': 2, 'asm': 'RES 4,A'}
opcodes[0xCB][0xA8] = {'size': 2, 'asm': 'RES 5,B'}
opcodes[0xCB][0xA9] = {'size': 2, 'asm': 'RES 5,C'}
opcodes[0xCB][0xAA] = {'size': 2, 'asm': 'RES 5,D'}
opcodes[0xCB][0xAB] = {'size': 2, 'asm': 'RES 5,E'}
opcodes[0xCB][0xAC] = {'size': 2, 'asm': 'RES 5,H'}
opcodes[0xCB][0xAD] = {'size': 2, 'asm': 'RES 5,L'}
opcodes[0xCB][0xAE] = {'size': 2, 'asm': 'RES 5,(HL)'}
opcodes[0xCB][0xAF] = {'size': 2, 'asm': 'RES 5,A'}

opcodes[0xCB][0xB0] = {'size': 2, 'asm': 'RES 6,B'}
opcodes[0xCB][0xB1] = {'size': 2, 'asm': 'RES 6,C'}
opcodes[0xCB][0xB2] = {'size': 2, 'asm': 'RES 6,D'}
opcodes[0xCB][0xB3] = {'size': 2, 'asm': 'RES 6,E'}
opcodes[0xCB][0xB4] = {'size': 2, 'asm': 'RES 6,H'}
opcodes[0xCB][0xB5] = {'size': 2, 'asm': 'RES 6,L'}
opcodes[0xCB][0xB6] = {'size': 2, 'asm': 'RES 6,(HL)'}
opcodes[0xCB][0xB7] = {'size': 2, 'asm': 'RES 6,A'}
opcodes[0xCB][0xB8] = {'size': 2, 'asm': 'RES 7,B'}
opcodes[0xCB][0xB9] = {'size': 2, 'asm': 'RES 7,C'}
opcodes[0xCB][0xBA] = {'size': 2, 'asm': 'RES 7,D'}
opcodes[0xCB][0xBB] = {'size': 2, 'asm': 'RES 7,E'}
opcodes[0xCB][0xBC] = {'size': 2, 'asm': 'RES 7,H'}
opcodes[0xCB][0xBD] = {'size': 2, 'asm': 'RES 7,L'}
opcodes[0xCB][0xBE] = {'size': 2, 'asm': 'RES 7,(HL)'}
opcodes[0xCB][0xBF] = {'size': 2, 'asm': 'RES 7,A'}

opcodes[0xCB][0xC0] = {'size': 2, 'asm': 'SET 0,B'}
opcodes[0xCB][0xC1] = {'size': 2, 'asm': 'SET 0,C'}
opcodes[0xCB][0xC2] = {'size': 2, 'asm': 'SET 0,D'}
opcodes[0xCB][0xC3] = {'size': 2, 'asm': 'SET 0,E'}
opcodes[0xCB][0xC4] = {'size': 2, 'asm': 'SET 0,H'}
opcodes[0xCB][0xC5] = {'size': 2, 'asm': 'SET 0,L'}
opcodes[0xCB][0xC6] = {'size': 2, 'asm': 'SET 0,(HL)'}
opcodes[0xCB][0xC7] = {'size': 2, 'asm': 'SET 0,A'}
opcodes[0xCB][0xC8] = {'size': 2, 'asm': 'SET 1,B'}
opcodes[0xCB][0xC9] = {'size': 2, 'asm': 'SET 1,C'}
opcodes[0xCB][0xCA] = {'size': 2, 'asm': 'SET 1,D'}
opcodes[0xCB][0xCB] = {'size': 2, 'asm': 'SET 1,E'}
opcodes[0xCB][0xCC] = {'size': 2, 'asm': 'SET 1,H'}
opcodes[0xCB][0xCD] = {'size': 2, 'asm': 'SET 1,L'}
opcodes[0xCB][0xCE] = {'size': 2, 'asm': 'SET 1,(HL)'}
opcodes[0xCB][0xCF] = {'size': 2, 'asm': 'SET 1,A'}

opcodes[0xCB][0xD0] = {'size': 2, 'asm': 'SET 2,B'}
opcodes[0xCB][0xD1] = {'size': 2, 'asm': 'SET 2,C'}
opcodes[0xCB][0xD2] = {'size': 2, 'asm': 'SET 2,D'}
opcodes[0xCB][0xD3] = {'size': 2, 'asm': 'SET 2,E'}
opcodes[0xCB][0xD4] = {'size': 2, 'asm': 'SET 2,H'}
opcodes[0xCB][0xD5] = {'size': 2, 'asm': 'SET 2,L'}
opcodes[0xCB][0xD6] = {'size': 2, 'asm': 'SET 2,(HL)'}
opcodes[0xCB][0xD7] = {'size': 2, 'asm': 'SET 2,A'}
opcodes[0xCB][0xD8] = {'size': 2, 'asm': 'SET 3,B'}
opcodes[0xCB][0xD9] = {'size': 2, 'asm': 'SET 3,C'}
opcodes[0xCB][0xDA] = {'size': 2, 'asm': 'SET 3,D'}
opcodes[0xCB][0xDB] = {'size': 2, 'asm': 'SET 3,E'}
opcodes[0xCB][0xDC] = {'size': 2, 'asm': 'SET 3,H'}
opcodes[0xCB][0xDD] = {'size': 2, 'asm': 'SET 3,L'}
opcodes[0xCB][0xDE] = {'size': 2, 'asm': 'SET 3,(HL)'}
opcodes[0xCB][0xDF] = {'size': 2, 'asm': 'SET 3,A'}

opcodes[0xCB][0xE0] = {'size': 2, 'asm': 'SET 4,B'}
opcodes[0xCB][0xE1] = {'size': 2, 'asm': 'SET 4,C'}
opcodes[0xCB][0xE2] = {'size': 2, 'asm': 'SET 4,D'}
opcodes[0xCB][0xE3] = {'size': 2, 'asm': 'SET 4,E'}
opcodes[0xCB][0xE4] = {'size': 2, 'asm': 'SET 4,H'}
opcodes[0xCB][0xE5] = {'size': 2, 'asm': 'SET 4,L'}
opcodes[0xCB][0xE6] = {'size': 2, 'asm': 'SET 4,(HL)'}
opcodes[0xCB][0xE7] = {'size': 2, 'asm': 'SET 4,A'}
opcodes[0xCB][0xE8] = {'size': 2, 'asm': 'SET 5,B'}
opcodes[0xCB][0xE9] = {'size': 2, 'asm': 'SET 5,C'}
opcodes[0xCB][0xEA] = {'size': 2, 'asm': 'SET 5,D'}
opcodes[0xCB][0xEB] = {'size': 2, 'asm': 'SET 5,E'}
opcodes[0xCB][0xEC] = {'size': 2, 'asm': 'SET 5,H'}
opcodes[0xCB][0xED] = {'size': 2, 'asm': 'SET 5,L'}
opcodes[0xCB][0xEE] = {'size': 2, 'asm': 'SET 5,(HL)'}
opcodes[0xCB][0xEF] = {'size': 2, 'asm': 'SET 5,A'}

opcodes[0xCB][0xF0] = {'size': 2, 'asm': 'SET 6,B'}
opcodes[0xCB][0xF1] = {'size': 2, 'asm': 'SET 6,C'}
opcodes[0xCB][0xF2] = {'size': 2, 'asm': 'SET 6,D'}
opcodes[0xCB][0xF3] = {'size': 2, 'asm': 'SET 6,E'}
opcodes[0xCB][0xF4] = {'size': 2, 'asm': 'SET 6,H'}
opcodes[0xCB][0xF5] = {'size': 2, 'asm': 'SET 6,L'}
opcodes[0xCB][0xF6] = {'size': 2, 'asm': 'SET 6,(HL)'}
opcodes[0xCB][0xF7] = {'size': 2, 'asm': 'SET 6,A'}
opcodes[0xCB][0xF8] = {'size': 2, 'asm': 'SET 7,B'}
opcodes[0xCB][0xF9] = {'size': 2, 'asm': 'SET 7,C'}
opcodes[0xCB][0xFA] = {'size': 2, 'asm': 'SET 7,D'}
opcodes[0xCB][0xFB] = {'size': 2, 'asm': 'SET 7,E'}
opcodes[0xCB][0xFC] = {'size': 2, 'asm': 'SET 7,H'}
opcodes[0xCB][0xFD] = {'size': 2, 'asm': 'SET 7,L'}
opcodes[0xCB][0xFE] = {'size': 2, 'asm': 'SET 7,(HL)'}
opcodes[0xCB][0xFF] = {'size': 2, 'asm': 'SET 7,A'}

opcodes[0xDD][0x09] = {'size': 2, 'asm': 'ADD IX,BC'}

opcodes[0xDD][0x19] = {'size': 2, 'asm': 'ADD IX,DE'}

opcodes[0xDD][0x21] = {'size': 4, 'asm': 'LD IX,%'}
opcodes[0xDD][0x22] = {'size': 4, 'asm': 'LD (%),IX'}
opcodes[0xDD][0x23] = {'size': 2, 'asm': 'INC IX'}
opcodes[0xDD][0x24] = {'size': 2, 'asm': 'INC IXH'}
opcodes[0xDD][0x25] = {'size': 2, 'asm': 'DEC IXH'}
opcodes[0xDD][0x26] = {'size': 3, 'asm': 'LD IXH,%'}
opcodes[0xDD][0x29] = {'size': 2, 'asm': 'ADD IX,IX'}
opcodes[0xDD][0x2A] = {'size': 4, 'asm': 'LD IX,(%)'}
opcodes[0xDD][0x2B] = {'size': 2, 'asm': 'DEC IX'}
opcodes[0xDD][0x2C] = {'size': 2, 'asm': 'INC IXL'}
opcodes[0xDD][0x2D] = {'size': 2, 'asm': 'DEC IXL'}
opcodes[0xDD][0x2E] = {'size': 3, 'asm': 'LD IXL,%'}

opcodes[0xDD][0x34] = {'size': 3, 'asm': 'INC (IX%)'}
opcodes[0xDD][0x35] = {'size': 3, 'asm': 'DEC (IX%)'}
opcodes[0xDD][0x36] = {'size': 4, 'asm': 'LD (IX%),%'}
opcodes[0xDD][0x39] = {'size': 2, 'asm': 'ADD IX,SP'}

opcodes[0xDD][0x44] = {'size': 2, 'asm': 'LD B,IXH'}
opcodes[0xDD][0x45] = {'size': 2, 'asm': 'LD B,IXL'}
opcodes[0xDD][0x46] = {'size': 3, 'asm': 'LD B,(IX%)'}
opcodes[0xDD][0x4C] = {'size': 2, 'asm': 'LD C,IXH'}
opcodes[0xDD][0x4D] = {'size': 2, 'asm': 'LD C,IXL'}
opcodes[0xDD][0x4E] = {'size': 3, 'asm': 'LD C,(IX%)'}

opcodes[0xDD][0x54] = {'size': 2, 'asm': 'LD D,IXH'}
opcodes[0xDD][0x55] = {'size': 2, 'asm': 'LD D,IXL'}
opcodes[0xDD][0x56] = {'size': 3, 'asm': 'LD D,(IX%)'}
opcodes[0xDD][0x5C] = {'size': 2, 'asm': 'LD E,IXH'}
opcodes[0xDD][0x5D] = {'size': 2, 'asm': 'LD E,IXL'}
opcodes[0xDD][0x5E] = {'size': 3, 'asm': 'LD E,(IX%)'}

opcodes[0xDD][0x60] = {'size': 2, 'asm': 'LD IXH,B'}
opcodes[0xDD][0x61] = {'size': 2, 'asm': 'LD IXH,C'}
opcodes[0xDD][0x62] = {'size': 2, 'asm': 'LD IXH,D'}
opcodes[0xDD][0x63] = {'size': 2, 'asm': 'LD IXH,E'}
opcodes[0xDD][0x64] = {'size': 2, 'asm': 'LD IXH,IXH'}
opcodes[0xDD][0x65] = {'size': 2, 'asm': 'LD IXH,IXL'}
opcodes[0xDD][0x66] = {'size': 3, 'asm': 'LD H,(IX%)'}
opcodes[0xDD][0x67] = {'size': 2, 'asm': 'LD IXH,A'}
opcodes[0xDD][0x68] = {'size': 2, 'asm': 'LD IXL,B'}
opcodes[0xDD][0x69] = {'size': 2, 'asm': 'LD IXL,C'}
opcodes[0xDD][0x6A] = {'size': 2, 'asm': 'LD IXL,D'}
opcodes[0xDD][0x6B] = {'size': 2, 'asm': 'LD IXL,E'}
opcodes[0xDD][0x6C] = {'size': 2, 'asm': 'LD IXL,IXH'}
opcodes[0xDD][0x6D] = {'size': 2, 'asm': 'LD IXL,IXL'}
opcodes[0xDD][0x6E] = {'size': 3, 'asm': 'LD L,(IX%)'}
opcodes[0xDD][0x6F] = {'size': 2, 'asm': 'LD IXL,A'}

opcodes[0xDD][0x70] = {'size': 3, 'asm': 'LD (IX%),B'}
opcodes[0xDD][0x71] = {'size': 3, 'asm': 'LD (IX%),C'}
opcodes[0xDD][0x72] = {'size': 3, 'asm': 'LD (IX%),D'}
opcodes[0xDD][0x73] = {'size': 3, 'asm': 'LD (IX%),E'}
opcodes[0xDD][0x74] = {'size': 3, 'asm': 'LD (IX%),H'}
opcodes[0xDD][0x75] = {'size': 3, 'asm': 'LD (IX%),L'}
opcodes[0xDD][0x77] = {'size': 3, 'asm': 'LD (IX%),A'}
opcodes[0xDD][0x7C] = {'size': 2, 'asm': 'LD A,IXH'}
opcodes[0xDD][0x7D] = {'size': 2, 'asm': 'LD A,IXL'}
opcodes[0xDD][0x7E] = {'size': 3, 'asm': 'LD A,(IX%)'}

opcodes[0xDD][0x84] = {'size': 2, 'asm': 'ADD IXH'}
opcodes[0xDD][0x85] = {'size': 2, 'asm': 'ADD IXL'}
opcodes[0xDD][0x86] = {'size': 3, 'asm': 'ADD (IX%)'}
opcodes[0xDD][0x8C] = {'size': 2, 'asm': 'ADC IXH'}
opcodes[0xDD][0x8D] = {'size': 2, 'asm': 'ADC IXL'}
opcodes[0xDD][0x8E] = {'size': 3, 'asm': 'ADC (IX%)'}

opcodes[0xDD][0x94] = {'size': 2, 'asm': 'SUB IXH'}
opcodes[0xDD][0x95] = {'size': 2, 'asm': 'SUB IXL'}
opcodes[0xDD][0x96] = {'size': 3, 'asm': 'SUB (IX%)'}
opcodes[0xDD][0x9C] = {'size': 2, 'asm': 'SBC IXH'}
opcodes[0xDD][0x9D] = {'size': 2, 'asm': 'SBC IXL'}
opcodes[0xDD][0x9E] = {'size': 3, 'asm': 'SBC (IX%)'}

opcodes[0xDD][0xA4] = {'size': 2, 'asm': 'AND IXH'}
opcodes[0xDD][0xA5] = {'size': 2, 'asm': 'AND IXL'}
opcodes[0xDD][0xA6] = {'size': 3, 'asm': 'AND (IX%)'}
opcodes[0xDD][0xAC] = {'size': 2, 'asm': 'XOR IXH'}
opcodes[0xDD][0xAD] = {'size': 2, 'asm': 'XOR IXL'}
opcodes[0xDD][0xAE] = {'size': 3, 'asm': 'XOR (IX%)'}

opcodes[0xDD][0xB4] = {'size': 2, 'asm': 'OR IXH'}
opcodes[0xDD][0xB5] = {'size': 2, 'asm': 'OR IXL'}
opcodes[0xDD][0xB6] = {'size': 3, 'asm': 'OR (IX%)'}
opcodes[0xDD][0xBC] = {'size': 2, 'asm': 'CP IXH'}
opcodes[0xDD][0xBD] = {'size': 2, 'asm': 'CP IXL'}
opcodes[0xDD][0xBE] = {'size': 3, 'asm': 'CP (IX%)'}

opcodes[0xDD][0xCB] = [None] * 256 + [1]

opcodes[0xDD][0xE1] = {'size': 2, 'asm': 'POP IX'}
opcodes[0xDD][0xE3] = {'size': 2, 'asm': 'EX (SP),IX'}
opcodes[0xDD][0xE5] = {'size': 2, 'asm': 'PUSH IX'}
opcodes[0xDD][0xE9] = {'size': 2, 'asm': 'JP (IX)'}

opcodes[0xDD][0xF9] = {'size': 2, 'asm': 'LD SP,IX'}

opcodes[0xDD][0xCB][0x00] = {'size': 4, 'asm': 'RLC (IX%),B'}
opcodes[0xDD][0xCB][0x01] = {'size': 4, 'asm': 'RLC (IX%),C'}
opcodes[0xDD][0xCB][0x02] = {'size': 4, 'asm': 'RLC (IX%),D'}
opcodes[0xDD][0xCB][0x03] = {'size': 4, 'asm': 'RLC (IX%),E'}
opcodes[0xDD][0xCB][0x04] = {'size': 4, 'asm': 'RLC (IX%),H'}
opcodes[0xDD][0xCB][0x05] = {'size': 4, 'asm': 'RLC (IX%),L'}
opcodes[0xDD][0xCB][0x06] = {'size': 4, 'asm': 'RLC (IX%)'}
opcodes[0xDD][0xCB][0x07] = {'size': 4, 'asm': 'RLC (IX%),A'}
opcodes[0xDD][0xCB][0x08] = {'size': 4, 'asm': 'RRC (IX%),B'}
opcodes[0xDD][0xCB][0x09] = {'size': 4, 'asm': 'RRC (IX%),C'}
opcodes[0xDD][0xCB][0x0A] = {'size': 4, 'asm': 'RRC (IX%),D'}
opcodes[0xDD][0xCB][0x0B] = {'size': 4, 'asm': 'RRC (IX%),E'}
opcodes[0xDD][0xCB][0x0C] = {'size': 4, 'asm': 'RRC (IX%),H'}
opcodes[0xDD][0xCB][0x0D] = {'size': 4, 'asm': 'RRC (IX%),L'}
opcodes[0xDD][0xCB][0x0E] = {'size': 4, 'asm': 'RRC (IX%)'}
opcodes[0xDD][0xCB][0x0F] = {'size': 4, 'asm': 'RRC (IX%),A'}

opcodes[0xDD][0xCB][0x10] = {'size': 4, 'asm': 'RL (IX%),B'}
opcodes[0xDD][0xCB][0x11] = {'size': 4, 'asm': 'RL (IX%),C'}
opcodes[0xDD][0xCB][0x12] = {'size': 4, 'asm': 'RL (IX%),D'}
opcodes[0xDD][0xCB][0x13] = {'size': 4, 'asm': 'RL (IX%),E'}
opcodes[0xDD][0xCB][0x14] = {'size': 4, 'asm': 'RL (IX%),H'}
opcodes[0xDD][0xCB][0x15] = {'size': 4, 'asm': 'RL (IX%),L'}
opcodes[0xDD][0xCB][0x16] = {'size': 4, 'asm': 'RL (IX%)'}
opcodes[0xDD][0xCB][0x17] = {'size': 4, 'asm': 'RL (IX%),A'}
opcodes[0xDD][0xCB][0x18] = {'size': 4, 'asm': 'RR (IX%),B'}
opcodes[0xDD][0xCB][0x19] = {'size': 4, 'asm': 'RR (IX%),C'}
opcodes[0xDD][0xCB][0x1A] = {'size': 4, 'asm': 'RR (IX%),D'}
opcodes[0xDD][0xCB][0x1B] = {'size': 4, 'asm': 'RR (IX%),E'}
opcodes[0xDD][0xCB][0x1C] = {'size': 4, 'asm': 'RR (IX%),H'}
opcodes[0xDD][0xCB][0x1D] = {'size': 4, 'asm': 'RR (IX%),L'}
opcodes[0xDD][0xCB][0x1E] = {'size': 4, 'asm': 'RR (IX%)'}
opcodes[0xDD][0xCB][0x1F] = {'size': 4, 'asm': 'RR (IX%),A'}

opcodes[0xDD][0xCB][0x20] = {'size': 4, 'asm': 'SLA (IX%),B'}
opcodes[0xDD][0xCB][0x21] = {'size': 4, 'asm': 'SLA (IX%),C'}
opcodes[0xDD][0xCB][0x22] = {'size': 4, 'asm': 'SLA (IX%),D'}
opcodes[0xDD][0xCB][0x23] = {'size': 4, 'asm': 'SLA (IX%),E'}
opcodes[0xDD][0xCB][0x24] = {'size': 4, 'asm': 'SLA (IX%),H'}
opcodes[0xDD][0xCB][0x25] = {'size': 4, 'asm': 'SLA (IX%),L'}
opcodes[0xDD][0xCB][0x26] = {'size': 4, 'asm': 'SLA (IX%)'}
opcodes[0xDD][0xCB][0x27] = {'size': 4, 'asm': 'SLA (IX%),A'}
opcodes[0xDD][0xCB][0x28] = {'size': 4, 'asm': 'SRA (IX%),B'}
opcodes[0xDD][0xCB][0x29] = {'size': 4, 'asm': 'SRA (IX%),C'}
opcodes[0xDD][0xCB][0x2A] = {'size': 4, 'asm': 'SRA (IX%),D'}
opcodes[0xDD][0xCB][0x2B] = {'size': 4, 'asm': 'SRA (IX%),E'}
opcodes[0xDD][0xCB][0x2C] = {'size': 4, 'asm': 'SRA (IX%),H'}
opcodes[0xDD][0xCB][0x2D] = {'size': 4, 'asm': 'SRA (IX%),L'}
opcodes[0xDD][0xCB][0x2E] = {'size': 4, 'asm': 'SRA (IX%)'}
opcodes[0xDD][0xCB][0x2F] = {'size': 4, 'asm': 'SRA (IX%),A'}

opcodes[0xDD][0xCB][0x30] = {'size': 4, 'asm': 'SLL (IX%),B'}
opcodes[0xDD][0xCB][0x31] = {'size': 4, 'asm': 'SLL (IX%),C'}
opcodes[0xDD][0xCB][0x32] = {'size': 4, 'asm': 'SLL (IX%),D'}
opcodes[0xDD][0xCB][0x33] = {'size': 4, 'asm': 'SLL (IX%),E'}
opcodes[0xDD][0xCB][0x34] = {'size': 4, 'asm': 'SLL (IX%),H'}
opcodes[0xDD][0xCB][0x35] = {'size': 4, 'asm': 'SLL (IX%),L'}
opcodes[0xDD][0xCB][0x36] = {'size': 4, 'asm': 'SLL (IX%)'}
opcodes[0xDD][0xCB][0x37] = {'size': 4, 'asm': 'SLL (IX%),A'}
opcodes[0xDD][0xCB][0x38] = {'size': 4, 'asm': 'SRL (IX%),B'}
opcodes[0xDD][0xCB][0x39] = {'size': 4, 'asm': 'SRL (IX%),C'}
opcodes[0xDD][0xCB][0x3A] = {'size': 4, 'asm': 'SRL (IX%),D'}
opcodes[0xDD][0xCB][0x3B] = {'size': 4, 'asm': 'SRL (IX%),E'}
opcodes[0xDD][0xCB][0x3C] = {'size': 4, 'asm': 'SRL (IX%),H'}
opcodes[0xDD][0xCB][0x3D] = {'size': 4, 'asm': 'SRL (IX%),L'}
opcodes[0xDD][0xCB][0x3E] = {'size': 4, 'asm': 'SRL (IX%)'}
opcodes[0xDD][0xCB][0x3F] = {'size': 4, 'asm': 'SRL (IX%),A'}

opcodes[0xDD][0xCB][0x40] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x41] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x42] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x43] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x44] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x45] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x46] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x47] = {'size': 4, 'asm': 'BIT 0,(IX%)'}
opcodes[0xDD][0xCB][0x48] = {'size': 4, 'asm': 'BIT 1,(IX%)'}
opcodes[0xDD][0xCB][0x49] = {'size': 4, 'asm': 'BIT 1,(IX%)'}
opcodes[0xDD][0xCB][0x4A] = {'size': 4, 'asm': 'BIT 1,(IX%)'}
opcodes[0xDD][0xCB][0x4B] = {'size': 4, 'asm': 'BIT 1,(IX%)'}
opcodes[0xDD][0xCB][0x4C] = {'size': 4, 'asm': 'BIT 1,(IX%)'}
opcodes[0xDD][0xCB][0x4D] = {'size': 4, 'asm': 'BIT 1,(IX%)'}
opcodes[0xDD][0xCB][0x4E] = {'size': 4, 'asm': 'BIT 1,(IX%)'}
opcodes[0xDD][0xCB][0x4F] = {'size': 4, 'asm': 'BIT 1,(IX%)'}

opcodes[0xDD][0xCB][0x50] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x51] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x52] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x53] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x54] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x55] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x56] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x57] = {'size': 4, 'asm': 'BIT 2,(IX%)'}
opcodes[0xDD][0xCB][0x58] = {'size': 4, 'asm': 'BIT 3,(IX%)'}
opcodes[0xDD][0xCB][0x59] = {'size': 4, 'asm': 'BIT 3,(IX%)'}
opcodes[0xDD][0xCB][0x5A] = {'size': 4, 'asm': 'BIT 3,(IX%)'}
opcodes[0xDD][0xCB][0x5B] = {'size': 4, 'asm': 'BIT 3,(IX%)'}
opcodes[0xDD][0xCB][0x5C] = {'size': 4, 'asm': 'BIT 3,(IX%)'}
opcodes[0xDD][0xCB][0x5D] = {'size': 4, 'asm': 'BIT 3,(IX%)'}
opcodes[0xDD][0xCB][0x5E] = {'size': 4, 'asm': 'BIT 3,(IX%)'}
opcodes[0xDD][0xCB][0x5F] = {'size': 4, 'asm': 'BIT 3,(IX%)'}

opcodes[0xDD][0xCB][0x60] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x61] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x62] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x63] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x64] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x65] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x66] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x67] = {'size': 4, 'asm': 'BIT 4,(IX%)'}
opcodes[0xDD][0xCB][0x68] = {'size': 4, 'asm': 'BIT 5,(IX%)'}
opcodes[0xDD][0xCB][0x69] = {'size': 4, 'asm': 'BIT 5,(IX%)'}
opcodes[0xDD][0xCB][0x6A] = {'size': 4, 'asm': 'BIT 5,(IX%)'}
opcodes[0xDD][0xCB][0x6B] = {'size': 4, 'asm': 'BIT 5,(IX%)'}
opcodes[0xDD][0xCB][0x6C] = {'size': 4, 'asm': 'BIT 5,(IX%)'}
opcodes[0xDD][0xCB][0x6D] = {'size': 4, 'asm': 'BIT 5,(IX%)'}
opcodes[0xDD][0xCB][0x6E] = {'size': 4, 'asm': 'BIT 5,(IX%)'}
opcodes[0xDD][0xCB][0x6F] = {'size': 4, 'asm': 'BIT 5,(IX%)'}

opcodes[0xDD][0xCB][0x70] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x71] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x72] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x73] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x74] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x75] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x76] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x77] = {'size': 4, 'asm': 'BIT 6,(IX%)'}
opcodes[0xDD][0xCB][0x78] = {'size': 4, 'asm': 'BIT 7,(IX%)'}
opcodes[0xDD][0xCB][0x79] = {'size': 4, 'asm': 'BIT 7,(IX%)'}
opcodes[0xDD][0xCB][0x7A] = {'size': 4, 'asm': 'BIT 7,(IX%)'}
opcodes[0xDD][0xCB][0x7B] = {'size': 4, 'asm': 'BIT 7,(IX%)'}
opcodes[0xDD][0xCB][0x7C] = {'size': 4, 'asm': 'BIT 7,(IX%)'}
opcodes[0xDD][0xCB][0x7D] = {'size': 4, 'asm': 'BIT 7,(IX%)'}
opcodes[0xDD][0xCB][0x7E] = {'size': 4, 'asm': 'BIT 7,(IX%)'}
opcodes[0xDD][0xCB][0x7F] = {'size': 4, 'asm': 'BIT 7,(IX%)'}

opcodes[0xDD][0xCB][0x80] = {'size': 4, 'asm': 'RES 0,(IX%),B'}
opcodes[0xDD][0xCB][0x81] = {'size': 4, 'asm': 'RES 0,(IX%),C'}
opcodes[0xDD][0xCB][0x82] = {'size': 4, 'asm': 'RES 0,(IX%),D'}
opcodes[0xDD][0xCB][0x83] = {'size': 4, 'asm': 'RES 0,(IX%),E'}
opcodes[0xDD][0xCB][0x84] = {'size': 4, 'asm': 'RES 0,(IX%),H'}
opcodes[0xDD][0xCB][0x85] = {'size': 4, 'asm': 'RES 0,(IX%),L'}
opcodes[0xDD][0xCB][0x86] = {'size': 4, 'asm': 'RES 0,(IX%)'}
opcodes[0xDD][0xCB][0x87] = {'size': 4, 'asm': 'RES 0,(IX%),A'}
opcodes[0xDD][0xCB][0x88] = {'size': 4, 'asm': 'RES 1,(IX%),B'}
opcodes[0xDD][0xCB][0x89] = {'size': 4, 'asm': 'RES 1,(IX%),C'}
opcodes[0xDD][0xCB][0x8A] = {'size': 4, 'asm': 'RES 1,(IX%),D'}
opcodes[0xDD][0xCB][0x8B] = {'size': 4, 'asm': 'RES 1,(IX%),E'}
opcodes[0xDD][0xCB][0x8C] = {'size': 4, 'asm': 'RES 1,(IX%),H'}
opcodes[0xDD][0xCB][0x8D] = {'size': 4, 'asm': 'RES 1,(IX%),L'}
opcodes[0xDD][0xCB][0x8E] = {'size': 4, 'asm': 'RES 1,(IX%)'}
opcodes[0xDD][0xCB][0x8F] = {'size': 4, 'asm': 'RES 1,(IX%),A'}

opcodes[0xDD][0xCB][0x90] = {'size': 4, 'asm': 'RES 2,(IX%),B'}
opcodes[0xDD][0xCB][0x91] = {'size': 4, 'asm': 'RES 2,(IX%),C'}
opcodes[0xDD][0xCB][0x92] = {'size': 4, 'asm': 'RES 2,(IX%),D'}
opcodes[0xDD][0xCB][0x93] = {'size': 4, 'asm': 'RES 2,(IX%),E'}
opcodes[0xDD][0xCB][0x94] = {'size': 4, 'asm': 'RES 2,(IX%),H'}
opcodes[0xDD][0xCB][0x95] = {'size': 4, 'asm': 'RES 2,(IX%),L'}
opcodes[0xDD][0xCB][0x96] = {'size': 4, 'asm': 'RES 2,(IX%)'}
opcodes[0xDD][0xCB][0x97] = {'size': 4, 'asm': 'RES 2,(IX%),A'}
opcodes[0xDD][0xCB][0x98] = {'size': 4, 'asm': 'RES 3,(IX%),B'}
opcodes[0xDD][0xCB][0x99] = {'size': 4, 'asm': 'RES 3,(IX%),C'}
opcodes[0xDD][0xCB][0x9A] = {'size': 4, 'asm': 'RES 3,(IX%),D'}
opcodes[0xDD][0xCB][0x9B] = {'size': 4, 'asm': 'RES 3,(IX%),E'}
opcodes[0xDD][0xCB][0x9C] = {'size': 4, 'asm': 'RES 3,(IX%),H'}
opcodes[0xDD][0xCB][0x9D] = {'size': 4, 'asm': 'RES 3,(IX%),L'}
opcodes[0xDD][0xCB][0x9E] = {'size': 4, 'asm': 'RES 3,(IX%)'}
opcodes[0xDD][0xCB][0x9F] = {'size': 4, 'asm': 'RES 3,(IX%),A'}


opcodes[0xDD][0xCB][0xA0] = {'size': 4, 'asm': 'RES 4,(IX%),B'}
opcodes[0xDD][0xCB][0xA1] = {'size': 4, 'asm': 'RES 4,(IX%),C'}
opcodes[0xDD][0xCB][0xA2] = {'size': 4, 'asm': 'RES 4,(IX%),D'}
opcodes[0xDD][0xCB][0xA3] = {'size': 4, 'asm': 'RES 4,(IX%),E'}
opcodes[0xDD][0xCB][0xA4] = {'size': 4, 'asm': 'RES 4,(IX%),H'}
opcodes[0xDD][0xCB][0xA5] = {'size': 4, 'asm': 'RES 4,(IX%),L'}
opcodes[0xDD][0xCB][0xA6] = {'size': 4, 'asm': 'RES 4,(IX%)'}
opcodes[0xDD][0xCB][0xA7] = {'size': 4, 'asm': 'RES 4,(IX%),A'}
opcodes[0xDD][0xCB][0xA8] = {'size': 4, 'asm': 'RES 5,(IX%),B'}
opcodes[0xDD][0xCB][0xA9] = {'size': 4, 'asm': 'RES 5,(IX%),C'}
opcodes[0xDD][0xCB][0xAA] = {'size': 4, 'asm': 'RES 5,(IX%),D'}
opcodes[0xDD][0xCB][0xAB] = {'size': 4, 'asm': 'RES 5,(IX%),E'}
opcodes[0xDD][0xCB][0xAC] = {'size': 4, 'asm': 'RES 5,(IX%),H'}
opcodes[0xDD][0xCB][0xAD] = {'size': 4, 'asm': 'RES 5,(IX%),L'}
opcodes[0xDD][0xCB][0xAE] = {'size': 4, 'asm': 'RES 5,(IX%)'}
opcodes[0xDD][0xCB][0xAF] = {'size': 4, 'asm': 'RES 5,(IX%),A'}

opcodes[0xDD][0xCB][0xB0] = {'size': 4, 'asm': 'RES 6,(IX%),B'}
opcodes[0xDD][0xCB][0xB1] = {'size': 4, 'asm': 'RES 6,(IX%),C'}
opcodes[0xDD][0xCB][0xB2] = {'size': 4, 'asm': 'RES 6,(IX%),D'}
opcodes[0xDD][0xCB][0xB3] = {'size': 4, 'asm': 'RES 6,(IX%),E'}
opcodes[0xDD][0xCB][0xB4] = {'size': 4, 'asm': 'RES 6,(IX%),H'}
opcodes[0xDD][0xCB][0xB5] = {'size': 4, 'asm': 'RES 6,(IX%),L'}
opcodes[0xDD][0xCB][0xB6] = {'size': 4, 'asm': 'RES 6,(IX%)'}
opcodes[0xDD][0xCB][0xB7] = {'size': 4, 'asm': 'RES 6,(IX%),A'}
opcodes[0xDD][0xCB][0xB8] = {'size': 4, 'asm': 'RES 7,(IX%),B'}
opcodes[0xDD][0xCB][0xB9] = {'size': 4, 'asm': 'RES 7,(IX%),C'}
opcodes[0xDD][0xCB][0xBA] = {'size': 4, 'asm': 'RES 7,(IX%),D'}
opcodes[0xDD][0xCB][0xBB] = {'size': 4, 'asm': 'RES 7,(IX%),E'}
opcodes[0xDD][0xCB][0xBC] = {'size': 4, 'asm': 'RES 7,(IX%),H'}
opcodes[0xDD][0xCB][0xBD] = {'size': 4, 'asm': 'RES 7,(IX%),L'}
opcodes[0xDD][0xCB][0xBE] = {'size': 4, 'asm': 'RES 7,(IX%)'}
opcodes[0xDD][0xCB][0xBF] = {'size': 4, 'asm': 'RES 7,(IX%),A'}

opcodes[0xDD][0xCB][0xC0] = {'size': 4, 'asm': 'SET 0,(IX%),B'}
opcodes[0xDD][0xCB][0xC1] = {'size': 4, 'asm': 'SET 0,(IX%),C'}
opcodes[0xDD][0xCB][0xC2] = {'size': 4, 'asm': 'SET 0,(IX%),D'}
opcodes[0xDD][0xCB][0xC3] = {'size': 4, 'asm': 'SET 0,(IX%),E'}
opcodes[0xDD][0xCB][0xC4] = {'size': 4, 'asm': 'SET 0,(IX%),H'}
opcodes[0xDD][0xCB][0xC5] = {'size': 4, 'asm': 'SET 0,(IX%),L'}
opcodes[0xDD][0xCB][0xC6] = {'size': 4, 'asm': 'SET 0,(IX%)'}
opcodes[0xDD][0xCB][0xC7] = {'size': 4, 'asm': 'SET 0,(IX%),A'}
opcodes[0xDD][0xCB][0xC8] = {'size': 4, 'asm': 'SET 1,(IX%),B'}
opcodes[0xDD][0xCB][0xC9] = {'size': 4, 'asm': 'SET 1,(IX%),C'}
opcodes[0xDD][0xCB][0xCA] = {'size': 4, 'asm': 'SET 1,(IX%),D'}
opcodes[0xDD][0xCB][0xCB] = {'size': 4, 'asm': 'SET 1,(IX%),E'}
opcodes[0xDD][0xCB][0xCC] = {'size': 4, 'asm': 'SET 1,(IX%),H'}
opcodes[0xDD][0xCB][0xCD] = {'size': 4, 'asm': 'SET 1,(IX%),L'}
opcodes[0xDD][0xCB][0xCE] = {'size': 4, 'asm': 'SET 1,(IX%)'}
opcodes[0xDD][0xCB][0xCF] = {'size': 4, 'asm': 'SET 1,(IX%),A'}

opcodes[0xDD][0xCB][0xD0] = {'size': 4, 'asm': 'SET 2,(IX%),B'}
opcodes[0xDD][0xCB][0xD1] = {'size': 4, 'asm': 'SET 2,(IX%),C'}
opcodes[0xDD][0xCB][0xD2] = {'size': 4, 'asm': 'SET 2,(IX%),D'}
opcodes[0xDD][0xCB][0xD3] = {'size': 4, 'asm': 'SET 2,(IX%),E'}
opcodes[0xDD][0xCB][0xD4] = {'size': 4, 'asm': 'SET 2,(IX%),H'}
opcodes[0xDD][0xCB][0xD5] = {'size': 4, 'asm': 'SET 2,(IX%),L'}
opcodes[0xDD][0xCB][0xD6] = {'size': 4, 'asm': 'SET 2,(IX%)'}
opcodes[0xDD][0xCB][0xD7] = {'size': 4, 'asm': 'SET 2,(IX%),A'}
opcodes[0xDD][0xCB][0xD8] = {'size': 4, 'asm': 'SET 3,(IX%),B'}
opcodes[0xDD][0xCB][0xD9] = {'size': 4, 'asm': 'SET 3,(IX%),C'}
opcodes[0xDD][0xCB][0xDA] = {'size': 4, 'asm': 'SET 3,(IX%),D'}
opcodes[0xDD][0xCB][0xDB] = {'size': 4, 'asm': 'SET 3,(IX%),E'}
opcodes[0xDD][0xCB][0xDC] = {'size': 4, 'asm': 'SET 3,(IX%),H'}
opcodes[0xDD][0xCB][0xDD] = {'size': 4, 'asm': 'SET 3,(IX%),L'}
opcodes[0xDD][0xCB][0xDE] = {'size': 4, 'asm': 'SET 3,(IX%)'}
opcodes[0xDD][0xCB][0xDF] = {'size': 4, 'asm': 'SET 3,(IX%),A'}

opcodes[0xDD][0xCB][0xE0] = {'size': 4, 'asm': 'SET 4,(IX%),B'}
opcodes[0xDD][0xCB][0xE1] = {'size': 4, 'asm': 'SET 4,(IX%),C'}
opcodes[0xDD][0xCB][0xE2] = {'size': 4, 'asm': 'SET 4,(IX%),D'}
opcodes[0xDD][0xCB][0xE3] = {'size': 4, 'asm': 'SET 4,(IX%),E'}
opcodes[0xDD][0xCB][0xE4] = {'size': 4, 'asm': 'SET 4,(IX%),H'}
opcodes[0xDD][0xCB][0xE5] = {'size': 4, 'asm': 'SET 4,(IX%),L'}
opcodes[0xDD][0xCB][0xE6] = {'size': 4, 'asm': 'SET 4,(IX%)'}
opcodes[0xDD][0xCB][0xE7] = {'size': 4, 'asm': 'SET 4,(IX%),A'}
opcodes[0xDD][0xCB][0xE8] = {'size': 4, 'asm': 'SET 5,(IX%),B'}
opcodes[0xDD][0xCB][0xE9] = {'size': 4, 'asm': 'SET 5,(IX%),C'}
opcodes[0xDD][0xCB][0xEA] = {'size': 4, 'asm': 'SET 5,(IX%),D'}
opcodes[0xDD][0xCB][0xEB] = {'size': 4, 'asm': 'SET 5,(IX%),E'}
opcodes[0xDD][0xCB][0xEC] = {'size': 4, 'asm': 'SET 5,(IX%),H'}
opcodes[0xDD][0xCB][0xED] = {'size': 4, 'asm': 'SET 5,(IX%),L'}
opcodes[0xDD][0xCB][0xEE] = {'size': 4, 'asm': 'SET 5,(IX%)'}
opcodes[0xDD][0xCB][0xEF] = {'size': 4, 'asm': 'SET 5,(IX%),A'}

opcodes[0xDD][0xCB][0xF0] = {'size': 4, 'asm': 'SET 6,(IX%),B'}
opcodes[0xDD][0xCB][0xF1] = {'size': 4, 'asm': 'SET 6,(IX%),C'}
opcodes[0xDD][0xCB][0xF2] = {'size': 4, 'asm': 'SET 6,(IX%),D'}
opcodes[0xDD][0xCB][0xF3] = {'size': 4, 'asm': 'SET 6,(IX%),E'}
opcodes[0xDD][0xCB][0xF4] = {'size': 4, 'asm': 'SET 6,(IX%),H'}
opcodes[0xDD][0xCB][0xF5] = {'size': 4, 'asm': 'SET 6,(IX%),L'}
opcodes[0xDD][0xCB][0xF6] = {'size': 4, 'asm': 'SET 6,(IX%)'}
opcodes[0xDD][0xCB][0xF7] = {'size': 4, 'asm': 'SET 6,(IX%),A'}
opcodes[0xDD][0xCB][0xF8] = {'size': 4, 'asm': 'SET 7,(IX%),B'}
opcodes[0xDD][0xCB][0xF9] = {'size': 4, 'asm': 'SET 7,(IX%),C'}
opcodes[0xDD][0xCB][0xFA] = {'size': 4, 'asm': 'SET 7,(IX%),D'}
opcodes[0xDD][0xCB][0xFB] = {'size': 4, 'asm': 'SET 7,(IX%),E'}
opcodes[0xDD][0xCB][0xFC] = {'size': 4, 'asm': 'SET 7,(IX%),H'}
opcodes[0xDD][0xCB][0xFD] = {'size': 4, 'asm': 'SET 7,(IX%),L'}
opcodes[0xDD][0xCB][0xFE] = {'size': 4, 'asm': 'SET 7,(IX%)'}
opcodes[0xDD][0xCB][0xFF] = {'size': 4, 'asm': 'SET 7,(IX%),A'}

opcodes[0xFD][0x09] = {'size': 2, 'asm': 'ADD IY,BC'}

opcodes[0xFD][0x19] = {'size': 2, 'asm': 'ADD IY,DE'}

opcodes[0xFD][0x21] = {'size': 4, 'asm': 'LD IY,%'}
opcodes[0xFD][0x22] = {'size': 4, 'asm': 'LD (%),IY'}
opcodes[0xFD][0x23] = {'size': 2, 'asm': 'INC IY'}
opcodes[0xFD][0x24] = {'size': 2, 'asm': 'INC IYH'}
opcodes[0xFD][0x25] = {'size': 2, 'asm': 'DEC IYH'}
opcodes[0xFD][0x26] = {'size': 3, 'asm': 'LD IYH,%'}
opcodes[0xFD][0x29] = {'size': 2, 'asm': 'ADD IY,IY'}
opcodes[0xFD][0x2A] = {'size': 4, 'asm': 'LD IY,(%)'}
opcodes[0xFD][0x2B] = {'size': 2, 'asm': 'DEC IY'}
opcodes[0xFD][0x2C] = {'size': 2, 'asm': 'INC IYL'}
opcodes[0xFD][0x2D] = {'size': 2, 'asm': 'DEC IYL'}
opcodes[0xFD][0x2E] = {'size': 3, 'asm': 'LD IYL,%'}

opcodes[0xFD][0x34] = {'size': 3, 'asm': 'INC (IY%)'}
opcodes[0xFD][0x35] = {'size': 3, 'asm': 'DEC (IY%)'}
opcodes[0xFD][0x36] = {'size': 4, 'asm': 'LD (IY%),%'}
opcodes[0xFD][0x39] = {'size': 2, 'asm': 'ADD IY,SP'}

opcodes[0xFD][0x44] = {'size': 2, 'asm': 'LD B,IYH'}
opcodes[0xFD][0x45] = {'size': 2, 'asm': 'LD B,IYL'}
opcodes[0xFD][0x46] = {'size': 3, 'asm': 'LD B,(IY%)'}
opcodes[0xFD][0x4C] = {'size': 2, 'asm': 'LD C,IYH'}
opcodes[0xFD][0x4D] = {'size': 2, 'asm': 'LD C,IYL'}
opcodes[0xFD][0x4E] = {'size': 3, 'asm': 'LD C,(IY%)'}

opcodes[0xFD][0x54] = {'size': 2, 'asm': 'LD D,IYH'}
opcodes[0xFD][0x55] = {'size': 2, 'asm': 'LD D,IYL'}
opcodes[0xFD][0x56] = {'size': 3, 'asm': 'LD D,(IY%)'}
opcodes[0xFD][0x5C] = {'size': 2, 'asm': 'LD E,IYH'}
opcodes[0xFD][0x5D] = {'size': 2, 'asm': 'LD E,IYL'}
opcodes[0xFD][0x5E] = {'size': 3, 'asm': 'LD E,(IY%)'}

opcodes[0xFD][0x60] = {'size': 2, 'asm': 'LD IYH,B'}
opcodes[0xFD][0x61] = {'size': 2, 'asm': 'LD IYH,C'}
opcodes[0xFD][0x62] = {'size': 2, 'asm': 'LD IYH,D'}
opcodes[0xFD][0x63] = {'size': 2, 'asm': 'LD IYH,E'}
opcodes[0xFD][0x64] = {'size': 2, 'asm': 'LD IYH,IYH'}
opcodes[0xFD][0x65] = {'size': 2, 'asm': 'LD IYH,IYL'}
opcodes[0xFD][0x66] = {'size': 3, 'asm': 'LD H,(IY%)'}
opcodes[0xFD][0x67] = {'size': 2, 'asm': 'LD IYH,A'}
opcodes[0xFD][0x68] = {'size': 2, 'asm': 'LD IYL,B'}
opcodes[0xFD][0x69] = {'size': 2, 'asm': 'LD IYL,C'}
opcodes[0xFD][0x6A] = {'size': 2, 'asm': 'LD IYL,D'}
opcodes[0xFD][0x6B] = {'size': 2, 'asm': 'LD IYL,E'}
opcodes[0xFD][0x6C] = {'size': 2, 'asm': 'LD IYL,IYH'}
opcodes[0xFD][0x6D] = {'size': 2, 'asm': 'LD IYL,IYL'}
opcodes[0xFD][0x6E] = {'size': 3, 'asm': 'LD L,(IY%)'}
opcodes[0xFD][0x6F] = {'size': 2, 'asm': 'LD IYL,A'}

opcodes[0xFD][0x70] = {'size': 3, 'asm': 'LD (IY%),B'}
opcodes[0xFD][0x71] = {'size': 3, 'asm': 'LD (IY%),C'}
opcodes[0xFD][0x72] = {'size': 3, 'asm': 'LD (IY%),D'}
opcodes[0xFD][0x73] = {'size': 3, 'asm': 'LD (IY%),E'}
opcodes[0xFD][0x74] = {'size': 3, 'asm': 'LD (IY%),H'}
opcodes[0xFD][0x75] = {'size': 3, 'asm': 'LD (IY%),L'}
opcodes[0xFD][0x77] = {'size': 3, 'asm': 'LD (IY%),A'}
opcodes[0xFD][0x7C] = {'size': 2, 'asm': 'LD A,IYH'}
opcodes[0xFD][0x7D] = {'size': 2, 'asm': 'LD A,IYL'}
opcodes[0xFD][0x7E] = {'size': 3, 'asm': 'LD A,(IY%)'}

opcodes[0xFD][0x84] = {'size': 2, 'asm': 'ADD IYH'}
opcodes[0xFD][0x85] = {'size': 2, 'asm': 'ADD IYL'}
opcodes[0xFD][0x86] = {'size': 3, 'asm': 'ADD (IY%)'}
opcodes[0xFD][0x8C] = {'size': 2, 'asm': 'ADC IYH'}
opcodes[0xFD][0x8D] = {'size': 2, 'asm': 'ADC IYL'}
opcodes[0xFD][0x8E] = {'size': 3, 'asm': 'ADC (IY%)'}

opcodes[0xFD][0x94] = {'size': 2, 'asm': 'SUB IYH'}
opcodes[0xFD][0x95] = {'size': 2, 'asm': 'SUB IYL'}
opcodes[0xFD][0x96] = {'size': 3, 'asm': 'SUB (IY%)'}
opcodes[0xFD][0x9C] = {'size': 2, 'asm': 'SBC IYH'}
opcodes[0xFD][0x9D] = {'size': 2, 'asm': 'SBC IYL'}
opcodes[0xFD][0x9E] = {'size': 3, 'asm': 'SBC (IY%)'}

opcodes[0xFD][0xA4] = {'size': 2, 'asm': 'AND IYH'}
opcodes[0xFD][0xA5] = {'size': 2, 'asm': 'AND IYL'}
opcodes[0xFD][0xA6] = {'size': 3, 'asm': 'AND (IY%)'}
opcodes[0xFD][0xAC] = {'size': 2, 'asm': 'XOR IYH'}
opcodes[0xFD][0xAD] = {'size': 2, 'asm': 'XOR IYL'}
opcodes[0xFD][0xAE] = {'size': 3, 'asm': 'XOR (IY%)'}

opcodes[0xFD][0xB4] = {'size': 2, 'asm': 'OR IYH'}
opcodes[0xFD][0xB5] = {'size': 2, 'asm': 'OR IYL'}
opcodes[0xFD][0xB6] = {'size': 3, 'asm': 'OR (IY%)'}
opcodes[0xFD][0xBC] = {'size': 2, 'asm': 'CP IYH'}
opcodes[0xFD][0xBD] = {'size': 2, 'asm': 'CP IYL'}
opcodes[0xFD][0xBE] = {'size': 3, 'asm': 'CP (IY%)'}

opcodes[0xFD][0xCB] = [None] * 256 + [1]

opcodes[0xFD][0xE1] = {'size': 2, 'asm': 'POP IY'}
opcodes[0xFD][0xE3] = {'size': 2, 'asm': 'EX (SP),IY'}
opcodes[0xFD][0xE5] = {'size': 2, 'asm': 'PUSH IY'}
opcodes[0xFD][0xE9] = {'size': 2, 'asm': 'JP (IY)'}

opcodes[0xFD][0xF9] = {'size': 2, 'asm': 'LD SP,IY'}

opcodes[0xFD][0xCB][0x00] = {'size': 4, 'asm': 'RLC (IY%),B'}
opcodes[0xFD][0xCB][0x01] = {'size': 4, 'asm': 'RLC (IY%),C'}
opcodes[0xFD][0xCB][0x02] = {'size': 4, 'asm': 'RLC (IY%),D'}
opcodes[0xFD][0xCB][0x03] = {'size': 4, 'asm': 'RLC (IY%),E'}
opcodes[0xFD][0xCB][0x04] = {'size': 4, 'asm': 'RLC (IY%),H'}
opcodes[0xFD][0xCB][0x05] = {'size': 4, 'asm': 'RLC (IY%),L'}
opcodes[0xFD][0xCB][0x06] = {'size': 4, 'asm': 'RLC (IY%)'}
opcodes[0xFD][0xCB][0x07] = {'size': 4, 'asm': 'RLC (IY%),A'}
opcodes[0xFD][0xCB][0x08] = {'size': 4, 'asm': 'RRC (IY%),B'}
opcodes[0xFD][0xCB][0x09] = {'size': 4, 'asm': 'RRC (IY%),C'}
opcodes[0xFD][0xCB][0x0A] = {'size': 4, 'asm': 'RRC (IY%),D'}
opcodes[0xFD][0xCB][0x0B] = {'size': 4, 'asm': 'RRC (IY%),E'}
opcodes[0xFD][0xCB][0x0C] = {'size': 4, 'asm': 'RRC (IY%),H'}
opcodes[0xFD][0xCB][0x0D] = {'size': 4, 'asm': 'RRC (IY%),L'}
opcodes[0xFD][0xCB][0x0E] = {'size': 4, 'asm': 'RRC (IY%)'}
opcodes[0xFD][0xCB][0x0F] = {'size': 4, 'asm': 'RRC (IY%),A'}

opcodes[0xFD][0xCB][0x10] = {'size': 4, 'asm': 'RL (IY%),B'}
opcodes[0xFD][0xCB][0x11] = {'size': 4, 'asm': 'RL (IY%),C'}
opcodes[0xFD][0xCB][0x12] = {'size': 4, 'asm': 'RL (IY%),D'}
opcodes[0xFD][0xCB][0x13] = {'size': 4, 'asm': 'RL (IY%),E'}
opcodes[0xFD][0xCB][0x14] = {'size': 4, 'asm': 'RL (IY%),H'}
opcodes[0xFD][0xCB][0x15] = {'size': 4, 'asm': 'RL (IY%),L'}
opcodes[0xFD][0xCB][0x16] = {'size': 4, 'asm': 'RL (IY%)'}
opcodes[0xFD][0xCB][0x17] = {'size': 4, 'asm': 'RL (IY%),A'}
opcodes[0xFD][0xCB][0x18] = {'size': 4, 'asm': 'RR (IY%),B'}
opcodes[0xFD][0xCB][0x19] = {'size': 4, 'asm': 'RR (IY%),C'}
opcodes[0xFD][0xCB][0x1A] = {'size': 4, 'asm': 'RR (IY%),D'}
opcodes[0xFD][0xCB][0x1B] = {'size': 4, 'asm': 'RR (IY%),E'}
opcodes[0xFD][0xCB][0x1C] = {'size': 4, 'asm': 'RR (IY%),H'}
opcodes[0xFD][0xCB][0x1D] = {'size': 4, 'asm': 'RR (IY%),L'}
opcodes[0xFD][0xCB][0x1E] = {'size': 4, 'asm': 'RR (IY%)'}
opcodes[0xFD][0xCB][0x1F] = {'size': 4, 'asm': 'RR (IY%),A'}

opcodes[0xFD][0xCB][0x20] = {'size': 4, 'asm': 'SLA (IY%),B'}
opcodes[0xFD][0xCB][0x21] = {'size': 4, 'asm': 'SLA (IY%),C'}
opcodes[0xFD][0xCB][0x22] = {'size': 4, 'asm': 'SLA (IY%),D'}
opcodes[0xFD][0xCB][0x23] = {'size': 4, 'asm': 'SLA (IY%),E'}
opcodes[0xFD][0xCB][0x24] = {'size': 4, 'asm': 'SLA (IY%),H'}
opcodes[0xFD][0xCB][0x25] = {'size': 4, 'asm': 'SLA (IY%),L'}
opcodes[0xFD][0xCB][0x26] = {'size': 4, 'asm': 'SLA (IY%)'}
opcodes[0xFD][0xCB][0x27] = {'size': 4, 'asm': 'SLA (IY%),A'}
opcodes[0xFD][0xCB][0x28] = {'size': 4, 'asm': 'SRA (IY%),B'}
opcodes[0xFD][0xCB][0x29] = {'size': 4, 'asm': 'SRA (IY%),C'}
opcodes[0xFD][0xCB][0x2A] = {'size': 4, 'asm': 'SRA (IY%),D'}
opcodes[0xFD][0xCB][0x2B] = {'size': 4, 'asm': 'SRA (IY%),E'}
opcodes[0xFD][0xCB][0x2C] = {'size': 4, 'asm': 'SRA (IY%),H'}
opcodes[0xFD][0xCB][0x2D] = {'size': 4, 'asm': 'SRA (IY%),L'}
opcodes[0xFD][0xCB][0x2E] = {'size': 4, 'asm': 'SRA (IY%)'}
opcodes[0xFD][0xCB][0x2F] = {'size': 4, 'asm': 'SRA (IY%),A'}

opcodes[0xFD][0xCB][0x30] = {'size': 4, 'asm': 'SLL (IY%),B'}
opcodes[0xFD][0xCB][0x31] = {'size': 4, 'asm': 'SLL (IY%),C'}
opcodes[0xFD][0xCB][0x32] = {'size': 4, 'asm': 'SLL (IY%),D'}
opcodes[0xFD][0xCB][0x33] = {'size': 4, 'asm': 'SLL (IY%),E'}
opcodes[0xFD][0xCB][0x34] = {'size': 4, 'asm': 'SLL (IY%),H'}
opcodes[0xFD][0xCB][0x35] = {'size': 4, 'asm': 'SLL (IY%),L'}
opcodes[0xFD][0xCB][0x36] = {'size': 4, 'asm': 'SLL (IY%)'}
opcodes[0xFD][0xCB][0x37] = {'size': 4, 'asm': 'SLL (IY%),A'}
opcodes[0xFD][0xCB][0x38] = {'size': 4, 'asm': 'SRL (IY%),B'}
opcodes[0xFD][0xCB][0x39] = {'size': 4, 'asm': 'SRL (IY%),C'}
opcodes[0xFD][0xCB][0x3A] = {'size': 4, 'asm': 'SRL (IY%),D'}
opcodes[0xFD][0xCB][0x3B] = {'size': 4, 'asm': 'SRL (IY%),E'}
opcodes[0xFD][0xCB][0x3C] = {'size': 4, 'asm': 'SRL (IY%),H'}
opcodes[0xFD][0xCB][0x3D] = {'size': 4, 'asm': 'SRL (IY%),L'}
opcodes[0xFD][0xCB][0x3E] = {'size': 4, 'asm': 'SRL (IY%)'}
opcodes[0xFD][0xCB][0x3F] = {'size': 4, 'asm': 'SRL (IY%),A'}

opcodes[0xFD][0xCB][0x40] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x41] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x42] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x43] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x44] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x45] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x46] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x47] = {'size': 4, 'asm': 'BIT 0,(IY%)'}
opcodes[0xFD][0xCB][0x48] = {'size': 4, 'asm': 'BIT 1,(IY%)'}
opcodes[0xFD][0xCB][0x49] = {'size': 4, 'asm': 'BIT 1,(IY%)'}
opcodes[0xFD][0xCB][0x4A] = {'size': 4, 'asm': 'BIT 1,(IY%)'}
opcodes[0xFD][0xCB][0x4B] = {'size': 4, 'asm': 'BIT 1,(IY%)'}
opcodes[0xFD][0xCB][0x4C] = {'size': 4, 'asm': 'BIT 1,(IY%)'}
opcodes[0xFD][0xCB][0x4D] = {'size': 4, 'asm': 'BIT 1,(IY%)'}
opcodes[0xFD][0xCB][0x4E] = {'size': 4, 'asm': 'BIT 1,(IY%)'}
opcodes[0xFD][0xCB][0x4F] = {'size': 4, 'asm': 'BIT 1,(IY%)'}

opcodes[0xFD][0xCB][0x50] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x51] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x52] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x53] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x54] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x55] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x56] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x57] = {'size': 4, 'asm': 'BIT 2,(IY%)'}
opcodes[0xFD][0xCB][0x58] = {'size': 4, 'asm': 'BIT 3,(IY%)'}
opcodes[0xFD][0xCB][0x59] = {'size': 4, 'asm': 'BIT 3,(IY%)'}
opcodes[0xFD][0xCB][0x5A] = {'size': 4, 'asm': 'BIT 3,(IY%)'}
opcodes[0xFD][0xCB][0x5B] = {'size': 4, 'asm': 'BIT 3,(IY%)'}
opcodes[0xFD][0xCB][0x5C] = {'size': 4, 'asm': 'BIT 3,(IY%)'}
opcodes[0xFD][0xCB][0x5D] = {'size': 4, 'asm': 'BIT 3,(IY%)'}
opcodes[0xFD][0xCB][0x5E] = {'size': 4, 'asm': 'BIT 3,(IY%)'}
opcodes[0xFD][0xCB][0x5F] = {'size': 4, 'asm': 'BIT 3,(IY%)'}

opcodes[0xFD][0xCB][0x60] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x61] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x62] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x63] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x64] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x65] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x66] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x67] = {'size': 4, 'asm': 'BIT 4,(IY%)'}
opcodes[0xFD][0xCB][0x68] = {'size': 4, 'asm': 'BIT 5,(IY%)'}
opcodes[0xFD][0xCB][0x69] = {'size': 4, 'asm': 'BIT 5,(IY%)'}
opcodes[0xFD][0xCB][0x6A] = {'size': 4, 'asm': 'BIT 5,(IY%)'}
opcodes[0xFD][0xCB][0x6B] = {'size': 4, 'asm': 'BIT 5,(IY%)'}
opcodes[0xFD][0xCB][0x6C] = {'size': 4, 'asm': 'BIT 5,(IY%)'}
opcodes[0xFD][0xCB][0x6D] = {'size': 4, 'asm': 'BIT 5,(IY%)'}
opcodes[0xFD][0xCB][0x6E] = {'size': 4, 'asm': 'BIT 5,(IY%)'}
opcodes[0xFD][0xCB][0x6F] = {'size': 4, 'asm': 'BIT 5,(IY%)'}

opcodes[0xFD][0xCB][0x70] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x71] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x72] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x73] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x74] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x75] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x76] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x77] = {'size': 4, 'asm': 'BIT 6,(IY%)'}
opcodes[0xFD][0xCB][0x78] = {'size': 4, 'asm': 'BIT 7,(IY%)'}
opcodes[0xFD][0xCB][0x79] = {'size': 4, 'asm': 'BIT 7,(IY%)'}
opcodes[0xFD][0xCB][0x7A] = {'size': 4, 'asm': 'BIT 7,(IY%)'}
opcodes[0xFD][0xCB][0x7B] = {'size': 4, 'asm': 'BIT 7,(IY%)'}
opcodes[0xFD][0xCB][0x7C] = {'size': 4, 'asm': 'BIT 7,(IY%)'}
opcodes[0xFD][0xCB][0x7D] = {'size': 4, 'asm': 'BIT 7,(IY%)'}
opcodes[0xFD][0xCB][0x7E] = {'size': 4, 'asm': 'BIT 7,(IY%)'}
opcodes[0xFD][0xCB][0x7F] = {'size': 4, 'asm': 'BIT 7,(IY%)'}

opcodes[0xFD][0xCB][0x80] = {'size': 4, 'asm': 'RES 0,(IY%),B'}
opcodes[0xFD][0xCB][0x81] = {'size': 4, 'asm': 'RES 0,(IY%),C'}
opcodes[0xFD][0xCB][0x82] = {'size': 4, 'asm': 'RES 0,(IY%),D'}
opcodes[0xFD][0xCB][0x83] = {'size': 4, 'asm': 'RES 0,(IY%),E'}
opcodes[0xFD][0xCB][0x84] = {'size': 4, 'asm': 'RES 0,(IY%),H'}
opcodes[0xFD][0xCB][0x85] = {'size': 4, 'asm': 'RES 0,(IY%),L'}
opcodes[0xFD][0xCB][0x86] = {'size': 4, 'asm': 'RES 0,(IY%)'}
opcodes[0xFD][0xCB][0x87] = {'size': 4, 'asm': 'RES 0,(IY%),A'}
opcodes[0xFD][0xCB][0x88] = {'size': 4, 'asm': 'RES 1,(IY%),B'}
opcodes[0xFD][0xCB][0x89] = {'size': 4, 'asm': 'RES 1,(IY%),C'}
opcodes[0xFD][0xCB][0x8A] = {'size': 4, 'asm': 'RES 1,(IY%),D'}
opcodes[0xFD][0xCB][0x8B] = {'size': 4, 'asm': 'RES 1,(IY%),E'}
opcodes[0xFD][0xCB][0x8C] = {'size': 4, 'asm': 'RES 1,(IY%),H'}
opcodes[0xFD][0xCB][0x8D] = {'size': 4, 'asm': 'RES 1,(IY%),L'}
opcodes[0xFD][0xCB][0x8E] = {'size': 4, 'asm': 'RES 1,(IY%)'}
opcodes[0xFD][0xCB][0x8F] = {'size': 4, 'asm': 'RES 1,(IY%),A'}

opcodes[0xFD][0xCB][0x90] = {'size': 4, 'asm': 'RES 2,(IY%),B'}
opcodes[0xFD][0xCB][0x91] = {'size': 4, 'asm': 'RES 2,(IY%),C'}
opcodes[0xFD][0xCB][0x92] = {'size': 4, 'asm': 'RES 2,(IY%),D'}
opcodes[0xFD][0xCB][0x93] = {'size': 4, 'asm': 'RES 2,(IY%),E'}
opcodes[0xFD][0xCB][0x94] = {'size': 4, 'asm': 'RES 2,(IY%),H'}
opcodes[0xFD][0xCB][0x95] = {'size': 4, 'asm': 'RES 2,(IY%),L'}
opcodes[0xFD][0xCB][0x96] = {'size': 4, 'asm': 'RES 2,(IY%)'}
opcodes[0xFD][0xCB][0x97] = {'size': 4, 'asm': 'RES 2,(IY%),A'}
opcodes[0xFD][0xCB][0x98] = {'size': 4, 'asm': 'RES 3,(IY%),B'}
opcodes[0xFD][0xCB][0x99] = {'size': 4, 'asm': 'RES 3,(IY%),C'}
opcodes[0xFD][0xCB][0x9A] = {'size': 4, 'asm': 'RES 3,(IY%),D'}
opcodes[0xFD][0xCB][0x9B] = {'size': 4, 'asm': 'RES 3,(IY%),E'}
opcodes[0xFD][0xCB][0x9C] = {'size': 4, 'asm': 'RES 3,(IY%),H'}
opcodes[0xFD][0xCB][0x9D] = {'size': 4, 'asm': 'RES 3,(IY%),L'}
opcodes[0xFD][0xCB][0x9E] = {'size': 4, 'asm': 'RES 3,(IY%)'}
opcodes[0xFD][0xCB][0x9F] = {'size': 4, 'asm': 'RES 3,(IY%),A'}


opcodes[0xFD][0xCB][0xA0] = {'size': 4, 'asm': 'RES 4,(IY%),B'}
opcodes[0xFD][0xCB][0xA1] = {'size': 4, 'asm': 'RES 4,(IY%),C'}
opcodes[0xFD][0xCB][0xA2] = {'size': 4, 'asm': 'RES 4,(IY%),D'}
opcodes[0xFD][0xCB][0xA3] = {'size': 4, 'asm': 'RES 4,(IY%),E'}
opcodes[0xFD][0xCB][0xA4] = {'size': 4, 'asm': 'RES 4,(IY%),H'}
opcodes[0xFD][0xCB][0xA5] = {'size': 4, 'asm': 'RES 4,(IY%),L'}
opcodes[0xFD][0xCB][0xA6] = {'size': 4, 'asm': 'RES 4,(IY%)'}
opcodes[0xFD][0xCB][0xA7] = {'size': 4, 'asm': 'RES 4,(IY%),A'}
opcodes[0xFD][0xCB][0xA8] = {'size': 4, 'asm': 'RES 5,(IY%),B'}
opcodes[0xFD][0xCB][0xA9] = {'size': 4, 'asm': 'RES 5,(IY%),C'}
opcodes[0xFD][0xCB][0xAA] = {'size': 4, 'asm': 'RES 5,(IY%),D'}
opcodes[0xFD][0xCB][0xAB] = {'size': 4, 'asm': 'RES 5,(IY%),E'}
opcodes[0xFD][0xCB][0xAC] = {'size': 4, 'asm': 'RES 5,(IY%),H'}
opcodes[0xFD][0xCB][0xAD] = {'size': 4, 'asm': 'RES 5,(IY%),L'}
opcodes[0xFD][0xCB][0xAE] = {'size': 4, 'asm': 'RES 5,(IY%)'}
opcodes[0xFD][0xCB][0xAF] = {'size': 4, 'asm': 'RES 5,(IY%),A'}

opcodes[0xFD][0xCB][0xB0] = {'size': 4, 'asm': 'RES 6,(IY%),B'}
opcodes[0xFD][0xCB][0xB1] = {'size': 4, 'asm': 'RES 6,(IY%),C'}
opcodes[0xFD][0xCB][0xB2] = {'size': 4, 'asm': 'RES 6,(IY%),D'}
opcodes[0xFD][0xCB][0xB3] = {'size': 4, 'asm': 'RES 6,(IY%),E'}
opcodes[0xFD][0xCB][0xB4] = {'size': 4, 'asm': 'RES 6,(IY%),H'}
opcodes[0xFD][0xCB][0xB5] = {'size': 4, 'asm': 'RES 6,(IY%),L'}
opcodes[0xFD][0xCB][0xB6] = {'size': 4, 'asm': 'RES 6,(IY%)'}
opcodes[0xFD][0xCB][0xB7] = {'size': 4, 'asm': 'RES 6,(IY%),A'}
opcodes[0xFD][0xCB][0xB8] = {'size': 4, 'asm': 'RES 7,(IY%),B'}
opcodes[0xFD][0xCB][0xB9] = {'size': 4, 'asm': 'RES 7,(IY%),C'}
opcodes[0xFD][0xCB][0xBA] = {'size': 4, 'asm': 'RES 7,(IY%),D'}
opcodes[0xFD][0xCB][0xBB] = {'size': 4, 'asm': 'RES 7,(IY%),E'}
opcodes[0xFD][0xCB][0xBC] = {'size': 4, 'asm': 'RES 7,(IY%),H'}
opcodes[0xFD][0xCB][0xBD] = {'size': 4, 'asm': 'RES 7,(IY%),L'}
opcodes[0xFD][0xCB][0xBE] = {'size': 4, 'asm': 'RES 7,(IY%)'}
opcodes[0xFD][0xCB][0xBF] = {'size': 4, 'asm': 'RES 7,(IY%),A'}

opcodes[0xFD][0xCB][0xC0] = {'size': 4, 'asm': 'SET 0,(IY%),B'}
opcodes[0xFD][0xCB][0xC1] = {'size': 4, 'asm': 'SET 0,(IY%),C'}
opcodes[0xFD][0xCB][0xC2] = {'size': 4, 'asm': 'SET 0,(IY%),D'}
opcodes[0xFD][0xCB][0xC3] = {'size': 4, 'asm': 'SET 0,(IY%),E'}
opcodes[0xFD][0xCB][0xC4] = {'size': 4, 'asm': 'SET 0,(IY%),H'}
opcodes[0xFD][0xCB][0xC5] = {'size': 4, 'asm': 'SET 0,(IY%),L'}
opcodes[0xFD][0xCB][0xC6] = {'size': 4, 'asm': 'SET 0,(IY%)'}
opcodes[0xFD][0xCB][0xC7] = {'size': 4, 'asm': 'SET 0,(IY%),A'}
opcodes[0xFD][0xCB][0xC8] = {'size': 4, 'asm': 'SET 1,(IY%),B'}
opcodes[0xFD][0xCB][0xC9] = {'size': 4, 'asm': 'SET 1,(IY%),C'}
opcodes[0xFD][0xCB][0xCA] = {'size': 4, 'asm': 'SET 1,(IY%),D'}
opcodes[0xFD][0xCB][0xCB] = {'size': 4, 'asm': 'SET 1,(IY%),E'}
opcodes[0xFD][0xCB][0xCC] = {'size': 4, 'asm': 'SET 1,(IY%),H'}
opcodes[0xFD][0xCB][0xCD] = {'size': 4, 'asm': 'SET 1,(IY%),L'}
opcodes[0xFD][0xCB][0xCE] = {'size': 4, 'asm': 'SET 1,(IY%)'}
opcodes[0xFD][0xCB][0xCF] = {'size': 4, 'asm': 'SET 1,(IY%),A'}

opcodes[0xFD][0xCB][0xD0] = {'size': 4, 'asm': 'SET 2,(IY%),B'}
opcodes[0xFD][0xCB][0xD1] = {'size': 4, 'asm': 'SET 2,(IY%),C'}
opcodes[0xFD][0xCB][0xD2] = {'size': 4, 'asm': 'SET 2,(IY%),D'}
opcodes[0xFD][0xCB][0xD3] = {'size': 4, 'asm': 'SET 2,(IY%),E'}
opcodes[0xFD][0xCB][0xD4] = {'size': 4, 'asm': 'SET 2,(IY%),H'}
opcodes[0xFD][0xCB][0xD5] = {'size': 4, 'asm': 'SET 2,(IY%),L'}
opcodes[0xFD][0xCB][0xD6] = {'size': 4, 'asm': 'SET 2,(IY%)'}
opcodes[0xFD][0xCB][0xD7] = {'size': 4, 'asm': 'SET 2,(IY%),A'}
opcodes[0xFD][0xCB][0xD8] = {'size': 4, 'asm': 'SET 3,(IY%),B'}
opcodes[0xFD][0xCB][0xD9] = {'size': 4, 'asm': 'SET 3,(IY%),C'}
opcodes[0xFD][0xCB][0xDA] = {'size': 4, 'asm': 'SET 3,(IY%),D'}
opcodes[0xFD][0xCB][0xDB] = {'size': 4, 'asm': 'SET 3,(IY%),E'}
opcodes[0xFD][0xCB][0xDC] = {'size': 4, 'asm': 'SET 3,(IY%),H'}
opcodes[0xFD][0xCB][0xDD] = {'size': 4, 'asm': 'SET 3,(IY%),L'}
opcodes[0xFD][0xCB][0xDE] = {'size': 4, 'asm': 'SET 3,(IY%)'}
opcodes[0xFD][0xCB][0xDF] = {'size': 4, 'asm': 'SET 3,(IY%),A'}

opcodes[0xFD][0xCB][0xE0] = {'size': 4, 'asm': 'SET 4,(IY%),B'}
opcodes[0xFD][0xCB][0xE1] = {'size': 4, 'asm': 'SET 4,(IY%),C'}
opcodes[0xFD][0xCB][0xE2] = {'size': 4, 'asm': 'SET 4,(IY%),D'}
opcodes[0xFD][0xCB][0xE3] = {'size': 4, 'asm': 'SET 4,(IY%),E'}
opcodes[0xFD][0xCB][0xE4] = {'size': 4, 'asm': 'SET 4,(IY%),H'}
opcodes[0xFD][0xCB][0xE5] = {'size': 4, 'asm': 'SET 4,(IY%),L'}
opcodes[0xFD][0xCB][0xE6] = {'size': 4, 'asm': 'SET 4,(IY%)'}
opcodes[0xFD][0xCB][0xE7] = {'size': 4, 'asm': 'SET 4,(IY%),A'}
opcodes[0xFD][0xCB][0xE8] = {'size': 4, 'asm': 'SET 5,(IY%),B'}
opcodes[0xFD][0xCB][0xE9] = {'size': 4, 'asm': 'SET 5,(IY%),C'}
opcodes[0xFD][0xCB][0xEA] = {'size': 4, 'asm': 'SET 5,(IY%),D'}
opcodes[0xFD][0xCB][0xEB] = {'size': 4, 'asm': 'SET 5,(IY%),E'}
opcodes[0xFD][0xCB][0xEC] = {'size': 4, 'asm': 'SET 5,(IY%),H'}
opcodes[0xFD][0xCB][0xED] = {'size': 4, 'asm': 'SET 5,(IY%),L'}
opcodes[0xFD][0xCB][0xEE] = {'size': 4, 'asm': 'SET 5,(IY%)'}
opcodes[0xFD][0xCB][0xEF] = {'size': 4, 'asm': 'SET 5,(IY%),A'}

opcodes[0xFD][0xCB][0xF0] = {'size': 4, 'asm': 'SET 6,(IY%),B'}
opcodes[0xFD][0xCB][0xF1] = {'size': 4, 'asm': 'SET 6,(IY%),C'}
opcodes[0xFD][0xCB][0xF2] = {'size': 4, 'asm': 'SET 6,(IY%),D'}
opcodes[0xFD][0xCB][0xF3] = {'size': 4, 'asm': 'SET 6,(IY%),E'}
opcodes[0xFD][0xCB][0xF4] = {'size': 4, 'asm': 'SET 6,(IY%),H'}
opcodes[0xFD][0xCB][0xF5] = {'size': 4, 'asm': 'SET 6,(IY%),L'}
opcodes[0xFD][0xCB][0xF6] = {'size': 4, 'asm': 'SET 6,(IY%)'}
opcodes[0xFD][0xCB][0xF7] = {'size': 4, 'asm': 'SET 6,(IY%),A'}
opcodes[0xFD][0xCB][0xF8] = {'size': 4, 'asm': 'SET 7,(IY%),B'}
opcodes[0xFD][0xCB][0xF9] = {'size': 4, 'asm': 'SET 7,(IY%),C'}
opcodes[0xFD][0xCB][0xFA] = {'size': 4, 'asm': 'SET 7,(IY%),D'}
opcodes[0xFD][0xCB][0xFB] = {'size': 4, 'asm': 'SET 7,(IY%),E'}
opcodes[0xFD][0xCB][0xFC] = {'size': 4, 'asm': 'SET 7,(IY%),H'}
opcodes[0xFD][0xCB][0xFD] = {'size': 4, 'asm': 'SET 7,(IY%),L'}
opcodes[0xFD][0xCB][0xFE] = {'size': 4, 'asm': 'SET 7,(IY%)'}
opcodes[0xFD][0xCB][0xFF] = {'size': 4, 'asm': 'SET 7,(IY%),A'}


def _init_tail_args(table, pos = 0):
    pos += 1
    for op in table[0:256]:
        if op:
            if type(op) is list:
                _init_tail_args(op, pos + op[256])
            elif pos < op['size']:
                op['args'] = [{'pos': pos, 'size': op['size'] - pos}]
_init_tail_args(opcodes)

for i in 0x18, 0x20, 0x28, 0x30, 0x38, 0x10: # JRs & DJNZ
    opcodes[i]['args'][0]['relative'] = True

for table in opcodes[0xDD], opcodes[0xFD]: # IX & IY
    for op in table[0:256]:
        if type(op) is dict:
            if 'args' in op and op['args'][0]['size'] == 1:
                op['args'][0]['signed'] = True # IX+d & IY+d

    for op in table[0xCB][0:256]: # IX & IY bit instructions
        if type(op) is dict:
            op['args'] = [{'pos': 2, 'size': 1, 'signed': True}] # IX+d & IY+d

    table[0x36]['args'] = [{'pos': 2, 'size': 1, 'signed': True}, {'pos': 3, 'size': 1}] # LD (IX+d),n & LD (IY+d),n
